"""Generated bytes/ pages for program-identity and register fields."""

from __future__ import annotations

from typing import Any

from ..frame import (
    NAME_OFFSET,
    PROGRAM_NAME_EDITABLE_LENGTH,
    PROGRAM_NAME_LENGTH,
    REGISTER_BASIS_BLOB_LENGTH,
    REGISTER_BASIS_BLOB_OFFSET,
)
from ..kaitai_value_maps import (
    build_bank_index_value_map,
    build_register_bank_value_map,
    build_register_value_map,
)


def _page_shell(
    *,
    nav: str,
    title: str,
    today: str,
    source_line: str,
    offsets: str,
    encoding: str,
    confidence: str,
    role: str,
    description: str,
    body_sections: list[str],
) -> str:
    lines = [
        nav,
        f"# {title}",
        "",
        f"_Generated {today}. {source_line}_",
        "",
        "## SysEx summary",
        "",
        f"- **Offsets:** {offsets}",
        f"- **Encoding:** `{encoding}`",
        f"- **Confidence:** {confidence}",
        f"- **Role:** {role}",
        "- **Layout:** [byte map overview](../byte-map-overview.md) · "
        "[full map](../byte-map.md)",
        "",
        "## Description",
        "",
        description,
        "",
    ]
    lines.extend(body_sections)
    lines.extend(
        [
            "## Related",
            "",
            "- [Program identity](../program-identity.md) — name / bank / slot overview",
            "- [Register captures](../../../sysex/prog/edit/registers/README.md) — "
            "hold-EDIT register corpus",
            "- [Owner’s manual notes](../../../docs/manual-notes.md)",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )
    return "\n".join(lines)


def render_program_name_page(*, today: str, nav: str = "") -> str:
    pad_start = NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH
    pad_end = NAME_OFFSET + PROGRAM_NAME_LENGTH - 1
    return _page_shell(
        nav=nav,
        title="Program name",
        today=today,
        source_line=(
            "Factory presets under `sysex/prog/presets/` plus register "
            "hold-EDIT captures."
        ),
        offsets=f"{NAME_OFFSET}–{NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH - 1}",
        encoding="ascii_space_padded",
        confidence="high",
        role=(
            f"{PROGRAM_NAME_EDITABLE_LENGTH}-character editable ASCII label "
            "(manual); space-padded within this field"
        ),
        description=(
            "Front-panel / register label text stored as ASCII in the program "
            f"dump. The owner's manual documents a "
            f"**{PROGRAM_NAME_EDITABLE_LENGTH}-character** location display when "
            "naming a register. Significant glyphs live at offsets "
            f"**{NAME_OFFSET}–{NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH - 1}**; "
            f"trailing pad at **{pad_start}–{pad_end}** completes the "
            f"{PROGRAM_NAME_LENGTH}-byte wire window (see "
            "[program name pad](program-name-pad.md)). Factory preset dumps also "
            "space-pad through offset 87; Reg-backed hold-EDIT dumps reuse "
            "24–87 for the register basis blob instead."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Space-padded ASCII. Factory corpus: every preset name fits in "
            f"**{PROGRAM_NAME_EDITABLE_LENGTH}** significant characters "
            f"(offsets {pad_start}–{pad_end} always `0x20`).",
            "",
            "| Layer | Offsets | Length | Notes |",
            "|-------|---------|-------:|-------|",
            (
                f"| Editable label | {NAME_OFFSET}–"
                f"{NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH - 1} | "
                f"{PROGRAM_NAME_EDITABLE_LENGTH} | Manual rename limit |"
            ),
            (
                f"| Trailing pad | {pad_start}–{pad_end} | "
                f"{PROGRAM_NAME_LENGTH - PROGRAM_NAME_EDITABLE_LENGTH} | "
                "Always spaces in this corpus "
                "([program name pad](program-name-pad.md)) |"
            ),
            (
                f"| Wire window | {NAME_OFFSET}–"
                f"{NAME_OFFSET + PROGRAM_NAME_LENGTH - 1} | "
                f"{PROGRAM_NAME_LENGTH} | SysEx allocation |"
            ),
            "",
        ],
    )


def render_program_name_pad_page(*, today: str, nav: str = "") -> str:
    pad_start = NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH
    pad_end = NAME_OFFSET + PROGRAM_NAME_LENGTH - 1
    return _page_shell(
        nav=nav,
        title="Program name pad",
        today=today,
        source_line=(
            "Factory presets under `sysex/prog/presets/` (all dumps) and "
            "register fullsweep captures."
        ),
        offsets=f"{pad_start}–{pad_end}",
        encoding="raw_bytes",
        confidence="high",
        role=(
            f"Trailing space pad completing the {PROGRAM_NAME_LENGTH}-byte "
            "wire name window"
        ),
        description=(
            f"Offsets **{pad_start}–{pad_end}** are always `0x20` in this "
            "corpus. They are not part of the editable "
            f"{PROGRAM_NAME_EDITABLE_LENGTH}-character label "
            "([program name](program-name.md)); together with that field they "
            f"form the {PROGRAM_NAME_LENGTH}-byte SysEx name window before the "
            "register basis blob / factory space pad at offset 24."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "| Value | Bytes | Source |",
            "|-------|-------|--------|",
            "| space pad | `20 20` | dump (all factory + register captures) |",
            "",
        ],
    )


def render_register_bank_page(*, today: str, nav: str = "") -> str:
    value_map = build_register_bank_value_map()
    rows = []
    for entry in value_map["entries"]:
        enc = int(entry["encoded"])
        label = entry["label"]
        rows.append(
            f"| {label} | `{enc:02X}` | {enc} | dump |"
        )
    return _page_shell(
        nav=nav,
        title="Register bank",
        today=today,
        source_line=(
            "Register hold-EDIT captures under "
            "`sysex/prog/edit/registers/` (including "
            "`fullsweep-rooms-studio-a.syx`)."
        ),
        offsets="93",
        encoding="raw_u8",
        confidence="high",
        role=(
            "Manual **Bank** of the register **loaded as the running basis** "
            "(`B0`–`B4` = `00`–`04`); `00` on factory/parameter-series dumps"
        ),
        description=(
            "When a **User Register** is loaded as the running program "
            "basis, offset **93** stores the register **Bank** (owner's "
            "manual: 5 Banks of 10 Registers). Witnessed exhaustively as "
            "`00`–`04` in `fullsweep-rooms-studio-a.syx`. A **store alone "
            "does not update it**: the delay-edit and rename captures "
            "(stored to B1 R1 while the basis remained the factory program) "
            "read `00`, while `charset-b1s1-rt5s-stored.syx` reads `01` "
            "because B1 R0 was the active basis at dump time. Factory and "
            "parameter-series dumps keep this at `00`. Distinct from factory "
            "**program bank** at 88–89 / mirror 137. Pair with "
            "[register](register.md) at offset 95."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Witness sources: register-basis hold-EDIT dumps "
            "(`sysex/prog/edit/registers/`).",
            "",
            "| Label | Offset 93 | Decoded | Source |",
            "|-------|-----------|--------:|--------|",
            *rows,
            "",
            "## Notes",
            "",
            "- Hold-EDIT dumps use program bank word **11** at 88–89; "
            "register identity is only at **93/95**.",
            "- LCD `display` (146–147) does **not** encode Bank/Register "
            "(fullsweep stayed at 164).",
            "",
        ],
    )


def render_register_page(*, today: str, nav: str = "") -> str:
    value_map = build_register_value_map()
    rows = []
    for entry in value_map["entries"]:
        enc = int(entry["encoded"])
        label = entry["label"]
        rows.append(
            f"| Register {label} | `{enc:02X}` | {enc} | dump |"
        )
    return _page_shell(
        nav=nav,
        title="Register",
        today=today,
        source_line=(
            "Register hold-EDIT captures under "
            "`sysex/prog/edit/registers/` (including "
            "`fullsweep-rooms-studio-a.syx`)."
        ),
        offsets="95",
        encoding="raw_u8",
        confidence="high",
        role=(
            "Manual **Register** of the register **loaded as the running "
            "basis** (`0`–`9`); `00` on factory/parameter-series dumps"
        ),
        description=(
            "When a **User Register** is loaded as the running program "
            "basis, offset **95** stores the **Register** number within the "
            "bank (owner's manual: 10 registers per bank). Witnessed "
            "exhaustively as `00`–`09` in `fullsweep-rooms-studio-a.syx`. "
            "A **store alone does not update it** — see "
            "[register bank](register-bank.md) for the witness captures. "
            "Factory and parameter-series dumps keep this at `00`. Distinct "
            "from factory **program slot** at 90–91."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Witness sources: register-basis hold-EDIT dumps "
            "(`sysex/prog/edit/registers/`).",
            "",
            "| Label | Offset 95 | Decoded | Source |",
            "|-------|-----------|--------:|--------|",
            *rows,
            "",
            "## Notes",
            "",
            "- Filename convention in the corpus: `b0-…/slot-3.syx` means "
            "Bank 0, Register 3.",
            "- Reserved offset **96** stays `00` in witnessed captures.",
            "",
        ],
    )


def render_bank_index_page(*, today: str, nav: str = "") -> str:
    value_map = build_bank_index_value_map()
    rows = []
    for entry in value_map["entries"]:
        enc = int(entry["encoded"])
        rows.append(f"| {entry['label']} | `{enc:02X}` | {enc} | dump/manual |")
    return _page_shell(
        nav=nav,
        title="Bank index",
        today=today,
        source_line=(
            "Factory presets under `sysex/prog/presets/` (222 dumps), "
            "hold-EDIT captures, and the Bricasti MIDI app notes bank table."
        ),
        offsets="88–89 (mirror at 137)",
        encoding="nibble_hilo",
        confidence="high",
        role=(
            "Program bank of the running program (`nibble_hilo`); hold-EDIT "
            "sends always use **11** here while mirror **137** keeps the "
            "source bank"
        ),
        description=(
            "Offsets **88–89** carry the program bank as a `nibble_hilo` "
            "word (high nibble at 88). Factory banks are 0–10 in preset-list "
            "order; the MIDI app notes add receive-side banks 118–120. "
            "Offset **137** mirrors the bank's low nibble and, on hold-EDIT "
            "sends (bank word = 11), still carries the **source** bank. "
            "Favorite-loaded PROG dumps carry the source program's bank here "
            "— never the Favorites bank 119 (see "
            "[favorite slot](favorite-slot.md)). Full identity walkthrough: "
            "[program identity](../program-identity.md)."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "| Bank | Bytes 88–89 (low nibble) | Decoded | Source |",
            "|------|--------------------------|--------:|--------|",
            *rows,
            "",
            "## Notes",
            "",
            "- Banks 118–120 are **receive-side** (MIDI app notes): they "
            "never appear at 88–89 in dumps sent by the unit.",
            "- Mirror **137** equals the bank low nibble on PROG frames and "
            "the source bank on hold-EDIT frames (`sysex/prog/edit/`).",
            "",
        ],
    )


def render_program_slot_page(*, today: str, nav: str = "") -> str:
    return _page_shell(
        nav=nav,
        title="Program slot",
        today=today,
        source_line=(
            "Factory presets under `sysex/prog/presets/` (222 dumps, all "
            "banks/slots)."
        ),
        offsets="90–91",
        encoding="nibble_hilo",
        confidence="high",
        role=(
            "Program slot within the bank (`nibble_hilo`, preset-list "
            "order); stays the *source factory* slot on hold-EDIT dumps"
        ),
        description=(
            "Offsets **90–91** carry the program's slot within its bank as "
            "a `nibble_hilo` word (high nibble at 90), counting from 0 in "
            "factory preset-list order. Hold-EDIT dumps keep the source "
            "program's slot even though the bank word switches to 11; "
            "favorite-loaded PROG dumps carry the source program's slot "
            "(see [favorite slot](favorite-slot.md)). Register identity "
            "lives elsewhere ([register bank](register-bank.md) / "
            "[register](register.md)). Per-bank slot tables: "
            "[program identity](../program-identity.md) and "
            "[preset inventory](../preset-inventory.md)."
        ),
        body_sections=[
            "## Notes",
            "",
            "- Most banks use contiguous slots from 0; **Rooms** runs 0–35 "
            "on this unit (more than the published sheet).",
            "- Not a MIDI program-change number — program changes use the "
            "bank-select mapping in the MIDI app notes.",
            "",
        ],
    )


def render_panel_mode_flag_page(*, today: str, nav: str = "") -> str:
    return _page_shell(
        nav=nav,
        title="Panel mode flag",
        today=today,
        source_line=(
            "Menu-navigation captures under `sysex/prog/menus/` and the "
            "favorites session under `sysex/prog/favorites/`."
        ),
        offsets="92",
        encoding="raw_u8",
        confidence="high",
        role=(
            "Front-panel screen state at dump time: `00` idle / value edit, "
            "`02` parameter menu highlighted, `08` favorites screen shown"
        ),
        description=(
            "Offset **92** reflects what the front panel was showing when "
            "the dump was taken — UI state, not a program property. `00` = "
            "program screen (idle or while a value is being edited); `02` = "
            "a parameter menu is highlighted (pair with "
            "[selected menu index](selected-menu-index.md) at 98–99 and "
            "[display](display.md) at 146–147); `08` = the favorites screen "
            "is shown. Holding PROG while this reads `08` **commits pending "
            "edits into the favorite slot** (see `sysex/prog/favorites/`)."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "| Value | Meaning | Witness |",
            "|-------|---------|---------|",
            "| `00` | Idle / value edit on the program screen | "
            "`sysex/prog/menus/no menu.syx` |",
            "| `02` | Parameter menu highlighted | `sysex/prog/menus/` "
            "(one capture per menu) |",
            "| `08` | Favorites screen shown | `sysex/prog/favorites/` "
            "(hold-PROG from the favorites screen) |",
            "",
            "## Notes",
            "",
            "- Not persistent: leaving the favorites screen drops this back "
            "to `00`/`02` while [favorite slot](favorite-slot.md) at 94 "
            "keeps the favorite marker.",
            "- Disambiguates Reverb Time (menu index 0) from idle at 98–99.",
            "- Full idle/browse/edit byte tables: [ui-state.md](../ui-state.md).",
            "",
        ],
    )


def render_selected_menu_index_page(*, today: str, nav: str = "") -> str:
    from ..catalog import PROGRAM_PARAMETERS
    from .nav import parameter_slug

    rows = []
    for index, entry in enumerate(PROGRAM_PARAMETERS):
        folder = entry["folder_hint"]
        rows.append(
            f"| {index} | [{entry['name']}]({parameter_slug(folder)}.md) |"
        )
    return _page_shell(
        nav=nav,
        title="Selected menu index",
        today=today,
        source_line=(
            "Menu-navigation captures under `sysex/prog/menus/` (one "
            "capture per highlighted menu)."
        ),
        offsets="98–99",
        encoding="nibble_hilo",
        confidence="high",
        role=(
            "Front-panel menu position (`nibble_hilo`, 0–17) while a "
            "parameter menu is open; `00 00` when idle"
        ),
        description=(
            "Offsets **98–99** carry the highlighted front-panel menu as a "
            "`nibble_hilo` index matching the hardware menu order (identical "
            "to the catalog order below). UI state, not a program property. "
            "Reverb Time is index 0, so an idle dump and a Reverb-Time-"
            "highlighted dump both read `00 00` here — disambiguate with "
            "[panel mode flag](panel-mode-flag.md) at 92 (`02` = menu open)."
        ),
        body_sections=[
            "## Menu order",
            "",
            "| Index | Menu (parameter) |",
            "|------:|------------------|",
            *rows,
            "",
            "## Notes",
            "",
            "- The LCD cursor position is separate: [display](display.md) "
            "at 146–147.",
            "- Full idle/browse/edit byte tables: [ui-state.md](../ui-state.md).",
            "",
        ],
    )


def render_algorithm_family_flag_page(*, today: str, nav: str = "") -> str:
    return _page_shell(
        nav=nav,
        title="Algorithm/family flag",
        today=today,
        source_line=(
            "Corpus scan of all factory presets under `sysex/prog/presets/`."
        ),
        offsets="97 (mirror at 145)",
        encoding="raw_u8",
        confidence="medium",
        role=(
            "Algorithm/family flag from the factory corpus: Halls all `3`; "
            "most other presets `4`, with a few bank-leading exceptions "
            "also `3`"
        ),
        description=(
            "Offset **97** groups presets into two families: every Halls "
            "preset reads `3`; most other presets read `4`, with a few "
            "bank-leading exceptions also at `3` (Chambers Large Chamber, "
            "Plates Bright Plate, Rooms Studio A, Halls 2 Large Hall). "
            "Offset **145** mirrors it as `0` when 97 = `3` and `1` when "
            "97 = `4`. It is **not** a clean V1/V2 algorithm bit — the "
            "engine class lives at "
            "[engine/bank-class flag](engine-bank-class-flag.md) (offset "
            "130). Not a user parameter; no capture series moves it."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "| Offset 97 | Mirror 145 | Presets |",
            "|-----------|-----------:|---------|",
            "| `3` | `0` | All Halls; Chambers Large Chamber, Plates Bright "
            "Plate, Rooms Studio A, Halls 2 Large Hall |",
            "| `4` | `1` | All other factory presets in this corpus |",
            "",
            "## Notes",
            "",
            "- Background and manual context: "
            "[manual-notes.md](../../../docs/manual-notes.md).",
            "",
        ],
    )


def render_engine_bank_class_flag_page(*, today: str, nav: str = "") -> str:
    return _page_shell(
        nav=nav,
        title="Engine/bank-class flag",
        today=today,
        source_line=(
            "Corpus scan of all factory presets under `sysex/prog/presets/`."
        ),
        offsets="130 (companion 131–132)",
        encoding="raw_u8",
        confidence="medium",
        role=(
            "Engine/bank class: `0` classic V1 banks, `1` the V2 `* 2` "
            "banks, `2` NonLin"
        ),
        description=(
            "Offset **130** selects the engine/bank class of the running "
            "program: `0` on the classic banks (Halls…Spaces, V1 "
            "algorithm), `1` on the `* 2` banks (Halls 2…Spaces 2, V2 "
            "algorithm), `2` on NonLin. Most parameter-series dumps read "
            "`1` (captured from Large Church, Halls 2); the LF RT "
            "multiply/crossover series read `0` (Large Hall). The "
            "companion bytes **131–132** are fixed at `02 00` across this "
            "corpus. Distinct from the "
            "[algorithm/family flag](algorithm-family-flag.md) at 97/145."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "| Value | Banks | Algorithm |",
            "|------:|-------|-----------|",
            "| `0` | Halls, Plates, Rooms, Chambers, Ambience, Spaces | V1 |",
            "| `1` | Halls 2, Plates 2, Rooms 2, Spaces 2 | V2 |",
            "| `2` | NonLin | Non-linear (AMS-style) |",
            "",
            "## Notes",
            "",
            "- Bank identity itself is at [bank index](bank-index.md) "
            "(88–89 / mirror 137).",
            "- Manual context (V1 vs V2, NonLin engine): "
            "[manual-notes.md](../../../docs/manual-notes.md).",
            "",
        ],
    )


def render_favorite_slot_page(*, today: str, nav: str = "") -> str:
    rows = [
        f"| Favorite {slot} | `{(slot - 1) * 2:02X}` | {(slot - 1) * 2} | dump |"
        for slot in (1, 2, 3, 4)
    ]
    rows.append("| not from a favorite | `08` | 8 | dump (entire factory corpus) |")
    return _page_shell(
        nav=nav,
        title="Favorite slot",
        today=today,
        source_line=(
            "Favorites captures under `sysex/prog/favorites/` "
            "(Deep Ambience and Nonlin C sessions)."
        ),
        offsets="94",
        encoding="raw_u8",
        confidence="high",
        role=(
            "Favorite-source slot: `(slot - 1) * 2` for favorites 1–4 on "
            "PROG frames; `08` = not loaded from a favorite"
        ),
        description=(
            "When the running program was loaded from one of the four "
            "front-panel **favorite** shortcut slots, hold-PROG dumps carry "
            "the source slot at offset **94** as `(slot - 1) * 2` "
            "(`00`/`02`/`04`/`06`). The marker **persists across edits and "
            "panel-mode changes** — it survives dirtying the program and "
            "leaving the favorites screen. Every other witnessed program "
            "dump (factory presets, parameter series, register bases, and "
            "all hold-EDIT frames, which always use bank word 11) reads "
            "`08`, previously misread as a structure/version constant. "
            "Favorite-loaded PROG dumps otherwise carry the **source "
            "program identity** at 88–91 (never the MIDI-notes Favorites "
            "bank 119, which applies to receive only). The favorites "
            "**screen** state is flagged separately at offset 92 "
            "(panel-mode flag, `08` = favorites screen displayed)."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Witness sources: favorite-loaded hold-PROG dumps "
            "(`sysex/prog/favorites/`), all four slots.",
            "",
            "| Label | Offset 94 | Decoded | Source |",
            "|-------|-----------|--------:|--------|",
            *rows,
            "",
            "## Notes",
            "",
            "- Hold-EDIT dumps always read `08` here regardless of basis; "
            "the favorite marker appears on PROG frames only.",
            "- Favorites auto-commit pending edits on hold-PROG from the "
            "favorites screen — see "
            "[register basis blob](register-basis-blob.md) (Favorites "
            "carve-out) and `sysex/prog/favorites/README.md`.",
            "",
        ],
    )


# Blob fields whose payload twin is a sound-parameter page under bytes/.
_BLOB_PARAM_PAGE_LABELS = {
    "predelay",
    "reverb time",
    "diffusion",
    "density",
    "hf rt crossover",
    "lf rt multiply",
    "modulation",
    "early to reverb mix",
    "vlf cut",
    "early select",
    "early rolloff",
    "rolloff",
    "size",
    "hf rt multiply",
    "lf rt crossover",
    "delay level",
    "delay time",
    "delay modulation",
}


def _blob_payload_cell(field: Any) -> str:
    """Payload-twin cell for one blob field row (with page link)."""
    from .nav import parameter_slug

    if not field.payload_offsets:
        return "—"
    offs = list(field.payload_offsets)
    off_txt = f"{offs[0]}–{offs[-1]}" if len(offs) > 1 else str(offs[0])
    if field.id == "name":
        return f"[program name](program-name.md) @ {off_txt}"
    if field.label in _BLOB_PARAM_PAGE_LABELS:
        return f"[{field.label}]({parameter_slug(field.label)}.md) @ {off_txt}"
    if field.id == "source_bank":
        return f"[bank index mirror](bank-index.md) @ {off_txt}"
    if field.id == "engine_class":
        return f"[engine/bank-class flag](engine-bank-class-flag.md) @ {off_txt}"
    return off_txt


def render_register_basis_blob_page(*, today: str, nav: str = "") -> str:
    from ..prog.register_blob import (
        BLOB_BIT_LENGTH,
        INFERRED_CHARSET_CODES,
        REGISTER_BLOB_FIELDS,
        REGISTER_NAME_CHARSET,
    )

    start = REGISTER_BASIS_BLOB_OFFSET
    end = REGISTER_BASIS_BLOB_OFFSET + REGISTER_BASIS_BLOB_LENGTH - 1

    layout_rows = []
    for field in REGISTER_BLOB_FIELDS:
        bits = (
            f"{field.bit_offset}–{field.bit_end}"
            if field.bit_width > 1
            else str(field.bit_offset)
        )
        note = field.doc.split(". ")[0] if field.doc else ""
        layout_rows.append(
            f"| {bits} | {field.bit_width} | {field.label} | "
            f"{_blob_payload_cell(field)} | {note} |"
        )

    charset_rows = []
    for lo, hi, desc in (
        (0, 0, "space"),
        (1, 1, "`&`"),
        (2, 11, "digits `0`–`9`"),
        (12, 37, "uppercase `A`–`Z`"),
        (38, 63, "lowercase `a`–`z`"),
    ):
        chars = REGISTER_NAME_CHARSET[lo : hi + 1]
        code_txt = str(lo) if lo == hi else f"{lo}–{hi}"
        note = (
            "code 2 (`0`) inferred by continuity; all others witnessed"
            if any(c in INFERRED_CHARSET_CODES for c in range(lo, hi + 1))
            else "witnessed"
        )
        charset_rows.append(f"| {code_txt} | `{chars}` | {desc} | {note} |")

    return _page_shell(
        nav=nav,
        title="Register basis blob",
        today=today,
        source_line=(
            "Register hold-EDIT captures under "
            "`sysex/prog/edit/registers/` (fullsweep + witness samples) "
            "plus favorites captures under `sysex/prog/favorites/`. "
            "Layout table generated from `REGISTER_BLOB_FIELDS` in "
            "`m7_sysex.prog.register_blob`."
        ),
        offsets=f"{start}–{end}",
        encoding="nibble_bitstream",
        confidence="high",
        role=(
            "Bit-packed snapshot of the **stored register** (name, store "
            "counter, all 18 parameters incl. the V2 delay block); factory "
            "dumps space-pad this region with `0x20`"
        ),
        description=(
            "On Reg-backed hold-EDIT dumps, offsets "
            f"**{start}–{end}** hold a snapshot of the register as it was "
            "**stored**. Read the low nibble of each byte (4 bits per byte, "
            f"MSB first) as a {BLOB_BIT_LENGTH}-bit stream; the fields below "
            "were verified against every register-basis frame in the corpus "
            "(each matches the corresponding live payload field unless the "
            "register has unstored edits). For **register** bases the blob "
            "is untouched by live edits: payload bytes 100–139 track the "
            "edit buffer, the blob keeps the stored values (witness: "
            "`samples/charset-b1s1-rt5s-unstored-edit.syx`, where reverb "
            "time reads 5.0 s in the payload but the stored 1.0 s here). "
            "**Favorite** saves write the same blob layout (store counter "
            "always 0) and auto-commit pending edits on hold-PROG from the "
            "favorites screen — see the Favorites section below. Factory "
            "and parameter-series dumps space-pad this region (`0x20`), so "
            "check for nibble bytes before decoding."
        ),
        body_sections=[
            "## Bit layout",
            "",
            "Bits count from the first nibble (offset "
            f"{start} low nibble = bits 0–3). Field widths are provisional "
            "at boundaries where the leading bits were always zero in this "
            "corpus; positions/order are exact.",
            "",
            "| Bits | Width | Field | Payload twin | Notes |",
            "|------|------:|-------|--------------|-------|",
            *layout_rows,
            "",
            "## Name charset (6-bit)",
            "",
            "14 characters × 6-bit code, space-padded. Complete 64-entry "
            "charset, pinned down by `samples/charset-b1s1-renamed.syx` "
            "(register renamed to `&123456789ABCD`):",
            "",
            "| Codes | Characters | Range | Status |",
            "|-------|------------|-------|--------|",
            *charset_rows,
            "",
            "## Store-generation counter",
            "",
            "Bits 96–100 (wire offsets 48–49) increment each time the "
            "register slot is overwritten. Witness history:",
            "",
            "- `fullsweep-rooms-studio-a.syx`: 3 for B0 R0–R2, 2 for "
            "B0 R3–B1 R1, 1 for all remaining registers — matching the "
            "corpus capture history exactly (the only non-identity bytes "
            "that vary inside the fullsweep).",
            "- `samples/rooms-studio-a-b1s1-delay-edit.syx`: one more store "
            "to B1 R1 bumped its counter from 2 to 3 with the rest of the "
            "blob unchanged.",
            "- `samples/charset-b1s1-renamed.syx`: reads 5 — renaming "
            "stores twice.",
            "- `samples/charset-b1s1-rt5s-stored.syx`: targeted B1 R0 and "
            "reads exactly R0's expected next count, 3.",
            "",
            "## Stored snapshot semantics",
            "",
            "- **The blob snapshots the stored register values (not the "
            "factory source), delay block included.** After storing a "
            "program with reverb time edited to 5.0 s and the delay block "
            "engaged (`samples/charset-b1s1-rt5s-stored.syx`), the blob's "
            "reverb-time field reads encoded 76 (5.0 s, not the factory 10) "
            "and bits 197–211 carry delay level 15 / time 11 / mod 6, "
            "exactly matching the payload.",
            "- **Zero delay tail with delay in the payload** "
            "(`samples/rooms-studio-a-b1s1-delay-edit.syx`) means the store "
            "happened *before* the delay was dialed in: the delay lived "
            "only in the edit buffer, not in the stored register.",
            "- **Register identity at offsets 93/95 = the register "
            "currently loaded as the running basis** "
            "([register bank](register-bank.md) / [register](register.md)). "
            "A store alone does **not** update them: the delay-edit and "
            "rename captures (stored to B1 R1 while the basis remained the "
            "factory program) read `0/0`, while "
            "`charset-b1s1-rt5s-stored.syx` reads `1/0` because B1 R0 was "
            "the active basis at dump time.",
            "- **Consumers should prefer the blob over the payload when it "
            "is present.** The web UI does this on MIDI receive: when an "
            "incoming program dump carries a register basis frame, the "
            "stored blob values (and register name) replace the live "
            "payload bytes, so unstored edit-buffer values are not adopted "
            "(`applyRegisterBasis` in `web-ui/src/app/midiReceive.ts`). "
            "This stays safe for favorite bases: the blob converges on the "
            "committed slot values.",
            "",
            "## Favorites carve-out",
            "",
            "Front-panel **favorite** slots (`sysex/prog/favorites/`) reuse "
            "this blob layout with different lifecycle rules:",
            "",
            "- A favorite save writes a full blob snapshot with the "
            "store-generation counter always **0** (re-saves do not "
            "increment it — favorites do not participate in the per-slot "
            "counter).",
            "- Unstored edits stay payload-only per frame, but the favorite "
            "slot **auto-commits the edit buffer** (blob included) when a "
            "hold-PROG dump is taken while the favorites screen is "
            "displayed (offset 92 = `08`); waiting, a brief PROG press, and "
            "hold-PROG from other screens do not commit (witnesses: "
            "`nonlin-c/13-rt075-favscreen-hold-prog-commit.syx` vs "
            "captures 18/21).",
            "- Offsets **93/95** stay register-only: a favorite basis does "
            "not update them. The favorite source is flagged at offset "
            "**94** instead ([favorite slot](favorite-slot.md)).",
            "",
            "## Witness captures",
            "",
            "All under `sysex/prog/edit/registers/`:",
            "",
            "- `fullsweep-rooms-studio-a.syx` — 50 registers "
            "(Banks 0–4 × Registers 0–9), layout + store counter",
            "- `samples/rooms-studio-a-b1s1-delay-edit.syx` — counter bump; "
            "delay in payload only (stored before the delay was dialed in)",
            "- `samples/charset-b1s1-renamed.syx` — name `&123456789ABCD` "
            "pins charset codes 1–11",
            "- `samples/charset-b1s1-rt5s-unstored-edit.syx` — unstored "
            "5.0 s edit: payload diverges from blob",
            "- `samples/charset-b1s1-rt5s-stored.syx` — stored 5.0 s + "
            "delay: blob updates; locates the delay block at bits 197–211",
            "",
        ],
    )


IDENTITY_BYTE_PAGES: tuple[dict[str, Any], ...] = (
    {
        "name": "Bank index",
        "folder": "bank index",
        "slug": "bank-index",
        "sysex": "`88-89` · `nibble_hilo` · high",
        "description": (
            "Program bank of the running program (mirror at 137); hold-EDIT "
            "sends use 11 here while the mirror keeps the source bank."
        ),
        "render": render_bank_index_page,
    },
    {
        "name": "Program slot",
        "folder": "program slot",
        "slug": "program-slot",
        "sysex": "`90-91` · `nibble_hilo` · high",
        "description": (
            "Program slot within the bank (preset-list order, from 0); "
            "stays the source factory slot on hold-EDIT dumps."
        ),
        "render": render_program_slot_page,
    },
    {
        "name": "Panel mode flag",
        "folder": "panel mode flag",
        "slug": "panel-mode-flag",
        "sysex": "`92` · `raw_u8` · high",
        "description": (
            "Front-panel screen state: `00` idle/value edit, `02` menu "
            "highlighted, `08` favorites screen shown (UI state, not a "
            "program property)."
        ),
        "render": render_panel_mode_flag_page,
    },
    {
        "name": "Selected menu index",
        "folder": "selected menu index",
        "slug": "selected-menu-index",
        "sysex": "`98-99` · `nibble_hilo` · high",
        "description": (
            "Highlighted front-panel menu (0–17, hardware menu order) while "
            "a parameter menu is open; `00 00` when idle."
        ),
        "render": render_selected_menu_index_page,
    },
    {
        "name": "Algorithm/family flag",
        "folder": "algorithm family flag",
        "slug": "algorithm-family-flag",
        "sysex": "`97` · `raw_u8` · medium",
        "description": (
            "Corpus family flag (Halls all 3; most others 4), mirrored at "
            "145 — not a clean V1/V2 bit."
        ),
        "render": render_algorithm_family_flag_page,
    },
    {
        "name": "Engine/bank-class flag",
        "folder": "engine bank class flag",
        "slug": "engine-bank-class-flag",
        "sysex": "`130` · `raw_u8` · medium",
        "description": (
            "Engine/bank class: 0 classic V1 banks, 1 the V2 `* 2` banks, "
            "2 NonLin; companion 131–132 fixed at `02 00`."
        ),
        "render": render_engine_bank_class_flag_page,
    },
    {
        "name": "Program name",
        "folder": "program name",
        "slug": "program-name",
        "sysex": "`8-21` · `ascii_space_padded` · high",
        "description": (
            "14-character editable ASCII program/register label (manual); "
            "space-padded within offsets 8–21."
        ),
        "render": render_program_name_page,
    },
    {
        "name": "Program name pad",
        "folder": "program name pad",
        "slug": "program-name-pad",
        "sysex": "`22-23` · `raw_bytes` · high",
        "description": (
            "Trailing space pad (`20 20`) completing the 16-byte wire name "
            "window."
        ),
        "render": render_program_name_pad_page,
    },
    {
        "name": "Register basis blob",
        "folder": "register basis blob",
        "slug": "register-basis-blob",
        "sysex": "`24-87` · `nibble_bitstream` · high",
        "description": (
            "Bit-packed stored-register snapshot (name, store counter, all "
            "18 parameters incl. delay block); factory dumps space-pad this "
            "region."
        ),
        "render": render_register_basis_blob_page,
    },
    {
        "name": "Register bank",
        "folder": "register bank",
        "slug": "register-bank",
        "sysex": "`93` · `raw_u8` · high",
        "description": (
            "User Registers Bank (manual B0–B4) when the dump basis is a "
            "register; see `sysex/prog/edit/registers/`."
        ),
        "render": render_register_bank_page,
    },
    {
        "name": "Register",
        "folder": "register",
        "slug": "register",
        "sysex": "`95` · `raw_u8` · high",
        "description": (
            "User Register number within bank (manual 0–9) when the dump "
            "basis is a register."
        ),
        "render": render_register_page,
    },
    {
        "name": "Favorite slot",
        "folder": "favorite slot",
        "slug": "favorite-slot",
        "sysex": "`94` · `raw_u8` · high",
        "description": (
            "Favorite-source slot (`(slot-1)*2` for favorites 1–4 on PROG "
            "frames; `08` = none); see `sysex/prog/favorites/`."
        ),
        "render": render_favorite_slot_page,
    },
)
