"""Generated bytes/ pages for program-identity and register fields."""

from __future__ import annotations

from typing import Any

from ..frame import (
    NAME_OFFSET,
    PROGRAM_NAME_EDITABLE_LENGTH,
    PROGRAM_NAME_LENGTH,
)
from ..kaitai_value_maps import (
    build_register_bank_value_map,
    build_register_value_map,
)


def _page_shell(
    *,
    nav: str,
    title: str,
    today: str,
    source_line: str,
    offsets: str,
    encoding: str,
    confidence: str,
    role: str,
    description: str,
    body_sections: list[str],
) -> str:
    lines = [
        nav,
        f"# {title}",
        "",
        f"_Generated {today}. {source_line}_",
        "",
        "## SysEx summary",
        "",
        f"- **Offsets:** {offsets}",
        f"- **Encoding:** `{encoding}`",
        f"- **Confidence:** {confidence}",
        f"- **Role:** {role}",
        "- **Layout:** [byte map overview](../byte-map-overview.md) · "
        "[full map](../byte-map.md)",
        "",
        "## Description",
        "",
        description,
        "",
    ]
    lines.extend(body_sections)
    lines.extend(
        [
            "## Related",
            "",
            "- [Program identity](../program-identity.md) — name / bank / slot overview",
            "- [Register captures](../../../sysex/prog/edit/registers/README.md) — "
            "hold-EDIT register corpus",
            "- [Owner’s manual notes](../../../docs/manual-notes.md)",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )
    return "\n".join(lines)


def render_program_name_page(*, today: str, nav: str = "") -> str:
    pad_start = NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH
    pad_end = NAME_OFFSET + PROGRAM_NAME_LENGTH - 1
    return _page_shell(
        nav=nav,
        title="Program name",
        today=today,
        source_line=(
            "Factory presets under `sysex/prog/presets/` plus register "
            "hold-EDIT captures."
        ),
        offsets=f"{NAME_OFFSET}–{NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH - 1}",
        encoding="ascii_space_padded",
        confidence="high",
        role=(
            f"{PROGRAM_NAME_EDITABLE_LENGTH}-character editable ASCII label "
            "(manual); space-padded within this field"
        ),
        description=(
            "Front-panel / register label text stored as ASCII in the program "
            f"dump. The owner's manual documents a "
            f"**{PROGRAM_NAME_EDITABLE_LENGTH}-character** location display when "
            "naming a register. Significant glyphs live at offsets "
            f"**{NAME_OFFSET}–{NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH - 1}**; "
            f"trailing pad at **{pad_start}–{pad_end}** completes the "
            f"{PROGRAM_NAME_LENGTH}-byte wire window (see "
            "[program name pad](program-name-pad.md)). Factory preset dumps also "
            "space-pad through offset 87; Reg-backed hold-EDIT dumps reuse "
            "24–87 for the register basis blob instead."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Space-padded ASCII. Factory corpus: every preset name fits in "
            f"**{PROGRAM_NAME_EDITABLE_LENGTH}** significant characters "
            f"(offsets {pad_start}–{pad_end} always `0x20`).",
            "",
            "| Layer | Offsets | Length | Notes |",
            "|-------|---------|-------:|-------|",
            (
                f"| Editable label | {NAME_OFFSET}–"
                f"{NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH - 1} | "
                f"{PROGRAM_NAME_EDITABLE_LENGTH} | Manual rename limit |"
            ),
            (
                f"| Trailing pad | {pad_start}–{pad_end} | "
                f"{PROGRAM_NAME_LENGTH - PROGRAM_NAME_EDITABLE_LENGTH} | "
                "Always spaces in this corpus "
                "([program name pad](program-name-pad.md)) |"
            ),
            (
                f"| Wire window | {NAME_OFFSET}–"
                f"{NAME_OFFSET + PROGRAM_NAME_LENGTH - 1} | "
                f"{PROGRAM_NAME_LENGTH} | SysEx allocation |"
            ),
            "",
        ],
    )


def render_program_name_pad_page(*, today: str, nav: str = "") -> str:
    pad_start = NAME_OFFSET + PROGRAM_NAME_EDITABLE_LENGTH
    pad_end = NAME_OFFSET + PROGRAM_NAME_LENGTH - 1
    return _page_shell(
        nav=nav,
        title="Program name pad",
        today=today,
        source_line=(
            "Factory presets under `sysex/prog/presets/` (all dumps) and "
            "register fullsweep captures."
        ),
        offsets=f"{pad_start}–{pad_end}",
        encoding="raw_bytes",
        confidence="high",
        role=(
            f"Trailing space pad completing the {PROGRAM_NAME_LENGTH}-byte "
            "wire name window"
        ),
        description=(
            f"Offsets **{pad_start}–{pad_end}** are always `0x20` in this "
            "corpus. They are not part of the editable "
            f"{PROGRAM_NAME_EDITABLE_LENGTH}-character label "
            "([program name](program-name.md)); together with that field they "
            f"form the {PROGRAM_NAME_LENGTH}-byte SysEx name window before the "
            "register basis blob / factory space pad at offset 24."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "| Value | Bytes | Source |",
            "|-------|-------|--------|",
            "| space pad | `20 20` | dump (all factory + register captures) |",
            "",
        ],
    )


def render_register_bank_page(*, today: str, nav: str = "") -> str:
    value_map = build_register_bank_value_map()
    rows = []
    for entry in value_map["entries"]:
        enc = int(entry["encoded"])
        label = entry["label"]
        rows.append(
            f"| {label} | `{enc:02X}` | {enc} | dump |"
        )
    return _page_shell(
        nav=nav,
        title="Register bank",
        today=today,
        source_line=(
            "Register hold-EDIT captures under "
            "`sysex/prog/edit/registers/` (including "
            "`fullsweep-rooms-studio-a.syx`)."
        ),
        offsets="93",
        encoding="raw_u8",
        confidence="high",
        role=(
            "Manual **Bank** within User Registers (`B0`–`B4` = `00`–`04`); "
            "`00` on factory/parameter-series dumps"
        ),
        description=(
            "When a **User Register** is the running program basis, offset "
            "**93** stores the register **Bank** (owner's manual: 5 Banks of "
            "10 Registers). Witnessed exhaustively as `00`–`04` in "
            "`fullsweep-rooms-studio-a.syx`. Factory and parameter-series "
            "dumps keep this at `00`. Distinct from factory **program bank** "
            "at 88–89 / mirror 137. Pair with [register](register.md) at "
            "offset 95."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Witness sources: register-basis hold-EDIT dumps "
            "(`sysex/prog/edit/registers/`).",
            "",
            "| Label | Offset 93 | Decoded | Source |",
            "|-------|-----------|--------:|--------|",
            *rows,
            "",
            "## Notes",
            "",
            "- Hold-EDIT dumps use program bank word **11** at 88–89; "
            "register identity is only at **93/95**.",
            "- LCD `display` (146–147) does **not** encode Bank/Register "
            "(fullsweep stayed at 164).",
            "",
        ],
    )


def render_register_page(*, today: str, nav: str = "") -> str:
    value_map = build_register_value_map()
    rows = []
    for entry in value_map["entries"]:
        enc = int(entry["encoded"])
        label = entry["label"]
        rows.append(
            f"| Register {label} | `{enc:02X}` | {enc} | dump |"
        )
    return _page_shell(
        nav=nav,
        title="Register",
        today=today,
        source_line=(
            "Register hold-EDIT captures under "
            "`sysex/prog/edit/registers/` (including "
            "`fullsweep-rooms-studio-a.syx`)."
        ),
        offsets="95",
        encoding="raw_u8",
        confidence="high",
        role=(
            "Manual **Register** within a register bank (`0`–`9`); "
            "`00` on factory/parameter-series dumps"
        ),
        description=(
            "When a **User Register** is the running program basis, offset "
            "**95** stores the **Register** number within the bank (owner's "
            "manual: 10 registers per bank). Witnessed exhaustively as "
            "`00`–`09` in `fullsweep-rooms-studio-a.syx`. Factory and "
            "parameter-series dumps keep this at `00`. Distinct from factory "
            "**program slot** at 90–91. Pair with "
            "[register bank](register-bank.md) at offset 93."
        ),
        body_sections=[
            "## Encoding map",
            "",
            "Witness sources: register-basis hold-EDIT dumps "
            "(`sysex/prog/edit/registers/`).",
            "",
            "| Label | Offset 95 | Decoded | Source |",
            "|-------|-----------|--------:|--------|",
            *rows,
            "",
            "## Notes",
            "",
            "- Filename convention in the corpus: `b0-…/slot-3.syx` means "
            "Bank 0, Register 3.",
            "- Reserved offset **96** stays `00` in witnessed captures.",
            "",
        ],
    )


IDENTITY_BYTE_PAGES: tuple[dict[str, Any], ...] = (
    {
        "name": "Program name",
        "folder": "program name",
        "slug": "program-name",
        "sysex": "`8-21` · `ascii_space_padded` · high",
        "description": (
            "14-character editable ASCII program/register label (manual); "
            "space-padded within offsets 8–21."
        ),
        "render": render_program_name_page,
    },
    {
        "name": "Program name pad",
        "folder": "program name pad",
        "slug": "program-name-pad",
        "sysex": "`22-23` · `raw_bytes` · high",
        "description": (
            "Trailing space pad (`20 20`) completing the 16-byte wire name "
            "window."
        ),
        "render": render_program_name_pad_page,
    },
    {
        "name": "Register bank",
        "folder": "register bank",
        "slug": "register-bank",
        "sysex": "`93` · `raw_u8` · high",
        "description": (
            "User Registers Bank (manual B0–B4) when the dump basis is a "
            "register; see `sysex/prog/edit/registers/`."
        ),
        "render": render_register_bank_page,
    },
    {
        "name": "Register",
        "folder": "register",
        "slug": "register",
        "sysex": "`95` · `raw_u8` · high",
        "description": (
            "User Register number within bank (manual 0–9) when the dump "
            "basis is a register."
        ),
        "render": render_register_page,
    },
)
