"""PROG (program-dump) documentation export."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path
from typing import Any, Sequence

from ..catalog import catalog_overview
from .nav import (
    _page_nav,
    bank_md_link,
    parameter_md_link,
    parameter_page_path,
    parameter_slug,
    preset_md_link,
    preset_slugs,
    prog_export_dir,
    resolve_export_dir,
    write_export_index,
)
from .open_items import PROG_OPEN_ITEMS, render_open_items_section

DOC_HEADER = """# M7 program-dump SysEx format

Community reverse-engineered specification from labeled hardware captures in this repository. Not an official Bricasti specification.

> Auto-generated by `python run.py` (or `python -m m7_sysex export`). Re-run after adding dumps; do not hand-edit generated pages.

"""

FRAME_SECTION = """## Frame layout

Observed length: **{message_length} bytes** for the captured program dumps.

| Offset | Size | Content |
|--------|------|---------|
| 0 | 1 | `F0` SysEx start |
| 1-3 | 3 | Manufacturer ID `{mfr}` (Bricasti Design) |
| 4-7 | 4 | Header `{header}` (program-dump family; exact semantics TBD) |
| 8-87 | 80 | Program name, ASCII, space-padded (preset title only) |
| 88-89 | 2 | Bank index (`nibble_hilo`) — see [program-identity.md](program-identity.md) |
| 90-91 | 2 | Program slot within bank (`nibble_hilo`) |
| 92-151 | 60 | Remaining parameter / state payload as **nibbles** (`0x00`-`0x0F`) |
| 152-155 | 4 | Checksum: **CRC-16/ARC** over offsets 8-151, packed as four high-nibble-first bytes |
| 156 | 1 | `F7` SysEx end |

```
F0 | {mfr} | {header} | <80-byte name> | <bank> <slot> <params...> | <4 nibble cs> | F7
```

### Notes

- All inspected payload bytes at offsets 88-155 stay within `0x00`-`0x0F`. That strongly suggests the M7 packs each binary byte as two MIDI nibbles rather than using classic 7-bit MIDI packing with MSB bitfields.
- Checksum (152-155): **CRC-16/ARC** over the raw SysEx bytes at offsets 8-151 (name + payload), packed as four high-nibble-first data bytes. Manufacturer ID and header are not covered.
- Program dumps can include UI / edit-state fields in addition to algorithm parameters (Bricasti documents that a program dump carries the running program, edits, and UI state). Expect a few offsets to move even during a “single parameter” series.
- **Independence:** each `sysex/prog/parameters/<parameter>/` folder is its own capture stream. Do not assume dumps from different folders share the same values for other parameters. Meta folder `sysex/prog/presets/` holds whole-preset dumps named `<bank>.<preset>` for identity fields.
- Edit-buffer dumps (hold **EDIT**) share the PROG header/length (157 bytes);
  bank word **88-89 = 11** while mirror **137** keeps the source bank. Keep them
  under `sysex/prog/edit/` — do not mix into parameter-series folders.
- Capture convention: wherever possible include usable **extremes**, the
  **adjacent-to-extreme** settings, and a **sparse sample of mids** (optional `off`).
  Mids are not a full list of every step. Name extremes as `low`/`high`/`full`
  or as the extreme numeric values (e.g. `0db.syx` ... `-20db.syx`).

## Nibble packing

Two consecutive SysEx bytes `A B` (each ≤ `0x0F`) can represent one 8-bit value in either order:

| Encoding | Formula | SysEx bytes for value `0x3A` |
|----------|---------|------------------------------|
| `nibble_hilo` | `(A << 4) \\| B` | `03 0A` |
| `nibble_lohi` | `A \\| (B << 4)` | `0A 03` |

The analyzer scores both against filename labels.

## Parameter map

| Parameter | Offsets | Encoding | Scale / notes | Range | Confidence | Dumps |
|-----------|---------|----------|---------------|-------|------------|-------|
"""

OPEN_QUESTIONS_FOOTER = """See [manual-notes.md](../../docs/manual-notes.md) for Bricasti manual/MIDI context (bank table, algorithms, dump types).

## Updating these pages

```bash
python run.py
# or: python -m m7_sysex export
```

This re-analyzes every folder under `sysex/`, refreshes each `analysis.json`, and regenerates this folder (`README.md`, `parameters/*.md`, program identity, byte map, Kaitai/`spec.json`, cross-series).

Cross-only (uses current analyses / dumps):

```bash
python -m m7_sysex cross
```
"""

ENCODING_MAP_INTRO_SHORT = (
    "Witness sources: [encoding sources](../../../docs/encoding-sources.md) "
    "(`dump`, `provided`, `inferred`, preset links)."
)

MAX_INLINE_PRESET_LINKS = 5











def export_sysex_format(
    results: list[dict[str, Any]],
    output_path: Path,
    byte_map: dict[str, Any] | None = None,
    cross: dict[str, Any] | None = None,
    names: dict[str, Any] | None = None,
    sheet_compare: dict[str, Any] | None = None,
) -> Path:
    """Write ``specification/prog/`` with overview + one page per parameter.

    Returns the prog overview README path.
    """
    if not results:
        raise ValueError("no analysis results to export")

    from ..cross import render_cross_markdown
    from ..provided import clear_provided_cache
    from ..preset_sheet import write_sheet_markdown

    # Always re-read docs/reference/provided_labels.json for this export.
    clear_provided_cache()

    if names is not None:
        from ..decode_preset import enrich_names_with_parameters

        enrich_names_with_parameters(names, results)

    output_root = resolve_export_dir(output_path)
    output_dir = prog_export_dir(output_root)
    output_dir.mkdir(parents=True, exist_ok=True)
    params_dir = output_dir / "parameters"
    params_dir.mkdir(parents=True, exist_ok=True)

    frame = results[0]["frame"]
    message_length = results[0]["message_length"]
    mfr = frame["manufacturer_id"]
    header = frame["header"]
    sorted_results = sorted(results, key=lambda r: r["parameter"])
    today = date.today().isoformat()

    overview = _render_overview_page(
        sorted_results,
        byte_map=byte_map,
        names=names,
        sheet_compare=sheet_compare,
        mfr=mfr,
        header=header,
        message_length=message_length,
        today=today,
    )
    overview_path = output_dir / "README.md"
    overview_path.write_text(overview, encoding="utf-8")

    folder = Path(results[0]["folder"])
    # ``folder`` is ``sysex/prog/parameters/<name>/`` in the type-first layout.
    sysex_root = folder.parent.parent.parent
    for result in sorted_results:
        page = _render_parameter_page(
            result,
            all_results=sorted_results,
            today=today,
            sysex_root=sysex_root,
        )
        parameter_page_path(output_dir, result["parameter"]).write_text(
            page, encoding="utf-8"
        )

    from .parameters_index import build_prog_parameters_readme

    sheet_decoders = (names or {}).get("parameter_decoders")
    (params_dir / "README.md").write_text(
        build_prog_parameters_readme(
            sorted_results,
            today=today,
            sheet_decoders=sheet_decoders,
        ),
        encoding="utf-8",
    )

    if names:
        series_names = {r["parameter"] for r in sorted_results}
        for dec in names.get("parameter_decoders") or []:
            if dec.get("source") != "preset_sheet":
                continue
            # Never clobber a full capture-series parameter page.
            if dec.get("parameter") in series_names:
                continue
            page = _render_sheet_only_parameter_page(dec, today=today)
            parameter_page_path(output_dir, dec["parameter"]).write_text(
                page, encoding="utf-8"
            )
        _export_preset_docs(
            output_dir, names, today=today, sheet_compare=sheet_compare
        )
        (output_dir / "program-identity.md").write_text(
            _render_names_page(names, today=today, sheet_compare=sheet_compare),
            encoding="utf-8",
        )

    if sheet_compare:
        write_sheet_markdown(
            sheet_compare,
            output_dir / "preset-sheet.md",
            today=today,
            nav=_page_nav(depth=0, current="Preset sheet"),
        )

    if byte_map:
        from ..byte_map import (
            render_byte_map_markdown,
            render_byte_map_overview_markdown,
        )
        from ..kaitai_spec import write_program_dump_spec

        overview_body = _promote_h1(render_byte_map_overview_markdown(byte_map))
        (output_dir / "byte-map-overview.md").write_text(
            _page_nav(depth=0, current="Byte map")
            + overview_body
            + f"\n\n_Last exported: {today}_\n",
            encoding="utf-8",
        )
        body = _promote_h1(render_byte_map_markdown(byte_map))
        (output_dir / "byte-map.md").write_text(
            _page_nav(depth=0) + body + f"\n\n_Last exported: {today}_\n",
            encoding="utf-8",
        )
        write_program_dump_spec(
            output_dir, byte_map, sorted_results, names=names
        )

    if cross:
        body = _promote_h1(render_cross_markdown(cross))
        (output_dir / "cross.md").write_text(
            _page_nav(depth=0) + body + f"\n\n_Last exported: {today}_\n",
            encoding="utf-8",
        )

    return overview_path



def _promote_h1(markdown: str) -> str:
    """Turn a leading ## heading into # for a standalone page."""
    if markdown.startswith("## "):
        return "#" + markdown[2:]
    return markdown



def _render_overview_page(
    results: list[dict[str, Any]],
    *,
    byte_map: dict[str, Any] | None,
    names: dict[str, Any] | None = None,
    sheet_compare: dict[str, Any] | None = None,
    mfr: str,
    header: str,
    message_length: int,
    today: str,
) -> str:
    parts: list[str] = [
        _page_nav(depth=0, current="Overview"),
        DOC_HEADER,
        _render_overview(
            results, byte_map, names=names, sheet_compare=sheet_compare
        ),
        "\n",
        FRAME_SECTION.format(
            message_length=message_length,
            mfr=mfr,
            header=header,
        ),
    ]

    for result in results:
        parts.append(_summary_row(result) + "\n")

    parts.append(
        "\n## Parameter pages\n\n"
        "Index of all parameters with manual descriptions: "
        "[parameters/README.md](parameters/README.md).\n"
    )
    parts.append(f"\n_Last exported: {today}_\n")
    parts.append(
        render_open_items_section(PROG_OPEN_ITEMS, footer=OPEN_QUESTIONS_FOOTER)
    )
    return "".join(parts)


def _render_overview(
    results: list[dict[str, Any]],
    byte_map: dict[str, Any] | None,
    names: dict[str, Any] | None = None,
    sheet_compare: dict[str, Any] | None = None,
) -> str:
    """High-level status driven by parameter fits + full byte map coverage."""
    from ..names import format_bank_map_by_index

    total_params = len(results)
    by_conf = {"high": [], "medium": [], "low": []}
    for result in sorted(results, key=lambda r: r["parameter"]):
        conf = (result.get("hypothesis") or {}).get("confidence") or "low"
        by_conf.setdefault(conf, [])
        best = result.get("best_encoding") or {}
        offsets = best.get("offsets") or []
        enc = best.get("encoding") or "?"
        slug = parameter_slug(result["parameter"])
        by_conf[conf].append(
            f"[`{result['parameter']}`](parameters/{slug}.md) @ "
            f"{_fmt_offsets(offsets)} (`{enc}`)"
        )

    lines: list[str] = [
        "## Overview",
        "",
        f"_Snapshot from export on {date.today().isoformat()}._",
        "",
        "Each `sysex/prog/parameters/<parameter>/` folder is an **independent** dump stream "
        "(only that parameter intentionally varied). Folders are never "
        "byte-compared against each other - other parameters may differ "
        "between series. Meta folder `sysex/prog/presets/` captures whole presets "
        "as `<bank>.<preset>.syx` for program-identity fields.",
        "",
    ]

    if names:
        hyp = names.get("hypothesis") or {}
        bank_map = ((names.get("fields") or {}).get("bank_index") or {}).get("map") or {}
        bank_bits = format_bank_map_by_index(bank_map)
        lines.extend(
            [
                "### Program identity (`sysex/prog/presets/`)",
                "",
                f"Confidence: **{hyp.get('confidence', '?')}**. "
                f"Details: [program-identity.md](program-identity.md) · "
                f"[presets/](presets/)"
                + (
                    " · [preset-sheet.md](preset-sheet.md)"
                    if sheet_compare
                    else ""
                )
                + ".",
                "",
                f"- Name field 8-87 matches filename preset ({names.get('dump_count', 0)} dumps).",
                f"- Bank index 88-89 (`nibble_hilo`): {bank_bits or '(see page)'}.",
                "- Program slot 90-91 (`nibble_hilo`) within the current bank.",
                "- Offset 137 mirrors bank index low nibble (89).",
                "",
            ]
        )
        if sheet_compare:
            lines.extend(
                [
                    f"- Sheet errata: **{sheet_compare.get('hard_count', 0)}** hard / "
                    f"**{sheet_compare.get('soft_only_count', 0)}** soft-only vs "
                    f"[Bricasti preset sheet](preset-sheet.md).",
                    "",
                ]
            )

    if byte_map:
        counts = byte_map["counts"]
        total = counts["total"] or 1
        known_pct = 100.0 * counts["known_or_frame"] / total
        unknown_pct = 100.0 * counts["unknown"] / total
        secondary_pct = 100.0 * counts["secondary"] / total
        lines.extend(
            [
                "### Byte coverage",
                "",
                f"Program-dump layout is **{total} bytes** "
                "(roles merged from independent per-parameter conclusions). "
                "Full table: [byte-map.md](byte-map.md) · "
                "short overview: [byte-map-overview.md](byte-map-overview.md). "
                "Codegen: [m7_program_dump.ksy](m7_program_dump.ksy) / "
                "[m7_program_dump.spec.json](m7_program_dump.spec.json).",
                "",
                "| Status | Bytes | Share |",
                "|--------|------:|------:|",
                f"| Known / frame / checksum | {counts['known_or_frame']} | {known_pct:.0f}% |",
                f"| Secondary (moved within a series) | {counts['secondary']} | {secondary_pct:.0f}% |",
                f"| Unknown | {counts['unknown']} | {unknown_pct:.0f}% |",
                "",
            ]
        )

        unknown_regions = [
            r for r in byte_map.get("regions") or [] if r.get("status") == "unknown"
        ]
        if unknown_regions:
            lines.append("Largest unknown payload regions:")
            lines.append("")
            for region in sorted(
                unknown_regions, key=lambda r: r["length"], reverse=True
            )[:5]:
                example = region.get("example_hex")
                suffix = f" - e.g. `{example}`" if example else ""
                lines.append(
                    f"- offsets **{region['offsets']}** "
                    f"({region['length']} byte{'s' if region['length'] != 1 else ''})"
                    f"{suffix}"
                )
            lines.append("")

        known_params = [
            r
            for r in byte_map.get("regions") or []
            if r.get("status") == "known"
        ]
        if known_params:
            from ..byte_map import _linkify_meaning, _series_parameter_names

            series_params = _series_parameter_names(byte_map)
            lines.append("Identified parameter fields (each from its own folder):")
            lines.append("")
            for region in known_params:
                role = _linkify_meaning(region["role"], series_params)
                lines.append(f"- **{region['offsets']}** - {role}")
            lines.append("")
    else:
        lines.extend(
            [
                "### Byte coverage",
                "",
                "_Byte map unavailable._",
                "",
            ]
        )

    lines.extend(
        [
            "### Parameter reverse-engineering",
            "",
            f"**{total_params}** parameter series analyzed under `sysex/prog/parameters/`.",
            "",
        ]
    )
    for conf in ("high", "medium", "low"):
        items = by_conf.get(conf) or []
        if not items:
            continue
        lines.append(f"- **{conf} confidence ({len(items)}):** {', '.join(items)}")
    lines.append("")

    overview = catalog_overview([r["parameter"] for r in results])
    lines.extend(
        [
            "### Official program parameters",
            "",
            overview["disclaimer"],
            "",
            f"Catalog hints: **{overview['program_parameter_count']}** published controls; "
            f"**{len(overview['captured'])}** matched to capture folders; "
            f"**{len(overview['missing'])}** still uncaptured.",
            "",
        ]
    )
    if overview["missing"]:
        lines.append("Still to capture (suggested folder names; ranges are hints):")
        lines.append("")
        for miss in overview["missing"]:
            lines.append(
                f"- `{miss['folder_hint']}` - {miss['name']} "
                f"({miss['range']})"
            )
        lines.append("")
        sheet_only = [
            d
            for d in ((names or {}).get("parameter_decoders") or [])
            if d.get("source") == "preset_sheet"
        ]
        if sheet_only:
            lines.append(
                "Already located via presets × published sheet "
                "(medium confidence until a dedicated series exists):"
            )
            lines.append("")
            for d in sheet_only:
                offs = d.get("offsets") or []
                off_txt = (
                    f"{offs[0]}-{offs[-1]}" if len(offs) > 1 else str(offs[0] if offs else "?")
                )
                lines.append(
                    f"- `{d['parameter']}` @ {off_txt} "
                    f"(`{d.get('encoding', '?')}`, {d.get('kind', '?')})"
                )
            lines.append("")
    lines.append("See also [parameter-catalog.md](../../docs/parameter-catalog.md).")
    lines.append("")

    lines.extend(
        [
            "### How to read these pages",
            "",
            "1. **This overview** - frame layout, parameter map, coverage.",
            "2. **[program-identity.md](program-identity.md)** / "
            "**[presets/](presets/)** - name / bank / slot; bank pages + "
            "[presets.json](presets/presets.json).",
            "3. **[preset-inventory.md](preset-inventory.md)** - capture count vs "
            "V2 addendum factory lists.",
            "4. **[preset-sheet.md](preset-sheet.md)** - errata vs Bricasti's "
            "published preset sheet PDF.",
            "5. **[parameters/README.md](parameters/README.md)** - all parameters with "
            "manual descriptions; each series also has dump tables and how-to-set notes "
            "under **[parameters/](parameters/)**.",
            "6. **[byte-map-overview.md](byte-map-overview.md)** / "
            "**[byte-map.md](byte-map.md)** - consolidated layout, then full detail.",
            "7. **[m7_program_dump.ksy](m7_program_dump.ksy)** / "
            "**[m7_program_dump.spec.json](m7_program_dump.spec.json)** - "
            "Kaitai Struct layout + machine schema for codegen.",
            "8. **[cross.md](cross.md)** - stable bytes, conflicts, coverage "
            "gaps across series.",
            "",
        ]
    )
    return "\n".join(lines)


def _export_preset_docs(
    output_dir: Path,
    names: dict[str, Any],
    *,
    today: str,
    sheet_compare: dict[str, Any] | None = None,
) -> int:
    """Write presets/ bank indexes, one page per preset, and presets.json."""
    from ..decode_preset import PARAMETER_ORDER

    sorted_dumps = sorted(
        names.get("dumps") or [],
        key=lambda row: (row.get("bank_index", 0), row.get("program_slot", 0)),
    )
    param_names = [
        p
        for p in PARAMETER_ORDER
        if any(p in (d.get("parameters") or {}) for d in sorted_dumps)
    ]
    decoders = names.get("parameter_decoders") or []

    by_bank: dict[str, list[dict[str, Any]]] = {}
    for d in sorted_dumps:
        by_bank.setdefault(d["bank"], []).append(d)

    presets_root = output_dir / "presets"
    presets_root.mkdir(parents=True, exist_ok=True)
    payload = {
        "generated": today,
        "source": "sysex/prog/presets/",
        "dump_count": len(sorted_dumps),
        "presets": sorted_dumps,
    }
    (presets_root / "presets.json").write_text(
        json.dumps(payload, indent=2) + "\n", encoding="utf-8"
    )

    for bank_name, dumps in by_bank.items():
        bank_slug, _ = preset_slugs(bank_name, dumps[0]["preset"])
        bank_folder = presets_root / bank_slug
        bank_folder.mkdir(parents=True, exist_ok=True)
        sorted_bank = sorted(dumps, key=lambda d: d.get("program_slot", 0))
        for dump in sorted_bank:
            _, preset_slug = preset_slugs(dump["bank"], dump["preset"])
            (bank_folder / f"{preset_slug}.md").write_text(
                _render_preset_page(
                    dump,
                    all_dumps=sorted_dumps,
                    bank_siblings=sorted_bank,
                    param_names=param_names,
                    decoders=decoders,
                    today=today,
                    sheet_compare=sheet_compare,
                ),
                encoding="utf-8",
            )
        (bank_folder / "README.md").write_text(
            _render_bank_page(
                bank_name,
                dumps,
                param_names=param_names,
                decoders=decoders,
                today=today,
                sheet_compare=sheet_compare,
            ),
            encoding="utf-8",
        )

    (presets_root / "README.md").write_text(
        _render_presets_index(sorted_dumps, today=today),
        encoding="utf-8",
    )
    return len(sorted_dumps)


def _preset_sheet_callout(
    sheet_status: dict[str, Any], *, link_prefix: str = "../../"
) -> list[str]:
    """Banner above the parameters table describing sheet coverage / errata."""
    kind = sheet_status.get("kind")
    if kind == "compared":
        comparison = sheet_status["comparison"]
        n_hard = len(comparison.get("hard") or [])
        n_soft = len(comparison.get("soft") or [])
        if n_hard or n_soft:
            parts: list[str] = []
            if n_hard:
                parts.append(f"{n_hard} hard")
            if n_soft:
                parts.append(f"{n_soft} soft")
            summary = " / ".join(parts)
            lines = [
                f"> **Sheet discrepancies ({summary}):** dump values disagree "
                "with the [published preset sheet]("
                f"{link_prefix}preset-sheet.md). "
                "Highlighted in the Status column below. "
                "**SysEx dump is authoritative.**",
                "",
            ]
            if n_hard:
                lines.append(
                    "> Hard = beyond tolerance (likely sheet print error or "
                    "unit/firmware variance)."
                )
            if n_soft:
                lines.append(
                    "> Soft = within table/rounding band (sparse-table "
                    "interpolation or print rounding)."
                )
            if n_hard or n_soft:
                lines.append("")
            return lines
        return [
            "> **Sheet comparison:** all printable sheet columns match the "
            "decoded dump (within tolerance).",
            "",
        ]
    if kind == "missing":
        return [
            "> **Not on the published sheet:** this factory dump has no row "
            "on the classic [preset sheet PDF]("
            f"{link_prefix}preset-sheet.md) "
            "(likely a later bank addition). Dump values only below.",
            "",
        ]
    if kind == "skipped":
        reason = sheet_status.get("reason") or "not listed on the classic sheet"
        return [
            f"> **Sheet comparison skipped:** {reason}. "
            f"See [preset-sheet.md]({link_prefix}preset-sheet.md). Dump values only "
            "below.",
            "",
        ]
    return []


def _format_sheet_delta(detail: dict[str, Any]) -> str:
    if "delta" not in detail:
        return ""
    try:
        delta = float(detail["delta"])
    except (TypeError, ValueError):
        return ""
    if abs(delta) < 1e-9:
        return ""
    if abs(delta - round(delta)) < 1e-9:
        return f" (Δ {int(round(delta)):+d})"
    text = f"{delta:+.4g}".rstrip("0").rstrip(".")
    return f" (Δ {text})"


def _preset_parameters_section(
    param_names: list[str],
    params: dict[str, Any],
    *,
    comparison: dict[str, Any] | None,
    comparable: Sequence[str],
    link_prefix: str = "../../",
) -> list[str]:
    """Dump vs printed-sheet parameter table with Status callouts."""
    detail_by_param = {
        d["param"]: d for d in (comparison.get("details") or [])
    } if comparison else {}
    comparable_set = set(comparable)

    lines = [
        "## Parameters",
        "",
        "Decoded from independent `sysex/prog/parameters/<parameter>/` series. "
        "`Dump` is the labeled value from the densified encoding map; `Encoded` "
        "is the raw step stored in SysEx. `~` means the step fell between "
        "labeled witnesses (rare once `provided` UI walks are merged).",
        "",
        "| Parameter | Dump | Encoded | Sheet | Status |",
        "|-----------|------|--------:|-------|--------|",
    ]

    for p in param_names:
        row = params.get(p) or {}
        dump_disp = row.get("display", "-")
        encoded = row.get("encoded", "-")
        link = f"[{p}]({link_prefix}parameters/{parameter_slug(p)}.md)"

        if p not in comparable_set:
            lines.append(
                f"| {link} | {dump_disp} | {encoded} | — | not on sheet |"
            )
            continue

        detail = detail_by_param.get(p)
        if detail is None:
            # Compared preset missing a detail row, or no sheet match at all.
            if comparison is None:
                lines.append(
                    f"| {link} | {dump_disp} | {encoded} | — | no sheet row |"
                )
            else:
                lines.append(
                    f"| {link} | {dump_disp} | {encoded} | — | skipped |"
                )
            continue

        sheet_disp = detail.get("sheet")
        if sheet_disp is None or sheet_disp == "":
            sheet_disp = "—"
        status = detail.get("status") or "skipped"
        if status == "match":
            status_txt = "match"
        elif status == "soft":
            status_txt = f"**soft**{_format_sheet_delta(detail)}"
        elif status == "hard":
            status_txt = f"**hard**{_format_sheet_delta(detail)}"
        else:
            status_txt = "skipped"

        lines.append(
            f"| {link} | {dump_disp} | {encoded} | {sheet_disp} | "
            f"{status_txt} |"
        )

    lines.append("")
    return lines


def _name_match_label(dump: dict[str, Any]) -> str:
    if dump.get("name_bytes_match"):
        return "(matches filename)"
    if dump.get("name_matches_preset"):
        return "(stripped name matches; padding/bytes differ)"
    return "(mismatch)"


def _name_bytes_label(dump: dict[str, Any]) -> str:
    if dump.get("name_bytes_match"):
        return "match filename preset (ASCII space-padded)"
    if dump.get("name_mismatch"):
        mm = dump["name_mismatch"]
        return (
            f"MISMATCH at offset {mm.get('offset')} "
            f"(expected `{mm.get('expected_byte')}`, got `{mm.get('actual_byte')}`)"
        )
    if dump.get("name_error"):
        return f"error: {dump['name_error']}"
    return "mismatch"


def _render_presets_index(dumps: list[dict[str, Any]], *, today: str) -> str:
    by_bank: dict[str, list[dict[str, Any]]] = {}
    for d in dumps:
        by_bank.setdefault(d["bank"], []).append(d)
    bank_order = sorted(
        by_bank.items(),
        key=lambda item: (item[1][0].get("bank_index", 0), item[0]),
    )

    lines = [
        _page_nav(depth=1, current="Program identity"),
        "# Presets",
        "",
        f"_Generated {today}. **{len(dumps)}** presets from `sysex/prog/presets/`._",
        "",
        "See also [program identity](../program-identity.md) for bank/slot "
        "fields and the cross-preset summary matrix. Machine-readable data: "
        "[presets.json](presets.json).",
        "",
        "## Banks",
        "",
        "| Bank | Index | Presets |",
        "|------|------:|--------:|",
    ]
    for bank, rows in bank_order:
        bank_slug, _ = preset_slugs(bank, rows[0]["preset"])
        lines.append(
            f"| [{bank}]({bank_slug}/) | {rows[0].get('bank_index')} | "
            f"{len(rows)} |"
        )
    lines.extend(
        [
            f"| **Total** | | **{len(dumps)}** |",
            "",
            "## All presets",
            "",
            "| Bank | Preset | Bank slot | Name bytes | Docs |",
            "|------|--------|----------:|------------|------|",
        ]
    )
    for d in dumps:
        bank_slug, preset_slug = preset_slugs(d["bank"], d["preset"])
        href = f"{bank_slug}/{preset_slug}.md"
        name_ok = "ok" if d.get("name_bytes_match") else "MISMATCH"
        lines.append(
            f"| [{d['bank']}]({bank_slug}/) | [{d['preset']}]({href}) | "
            f"{d.get('program_slot')} | {name_ok} | [{preset_slug}]({href}) |"
        )
    lines.extend(["", f"_Last exported: {today}_", ""])
    return "\n".join(lines)


def _render_bank_page(
    bank_name: str,
    dumps: list[dict[str, Any]],
    *,
    param_names: list[str],
    decoders: list[dict[str, Any]],
    today: str,
    sheet_compare: dict[str, Any] | None = None,
) -> str:
    bank_idx = dumps[0].get("bank_index")
    sorted_bank = sorted(dumps, key=lambda d: d.get("program_slot", 0))
    lines = [
        _page_nav(depth=2, current="Program identity"),
        f"# {bank_name}",
        "",
        f"_Generated {today}. Bank index **{bank_idx}** "
        f"({len(dumps)} captured preset{'s' if len(dumps) != 1 else ''})._",
        "",
        "Machine-readable dump list: [presets.json](../presets.json).",
        "",
        "## Presets",
        "",
        "| Slot | Preset |",
        "|-----:|--------|",
    ]
    for d in sorted_bank:
        _, preset_slug = preset_slugs(d["bank"], d["preset"])
        lines.append(
            f"| {d.get('program_slot')} | [{d['preset']}]({preset_slug}.md) |"
        )
    lines.append("")

    if decoders:
        lines.extend(
            [
                "## Decoder sources",
                "",
                "| Parameter | Offsets | Encoding | Kind |",
                "|-----------|---------|----------|------|",
            ]
        )
        for spec in decoders:
            offs = spec.get("offsets") or []
            if len(offs) == 1:
                off_txt = str(offs[0])
            elif offs:
                off_txt = f"{offs[0]}-{offs[-1]}"
            else:
                off_txt = "-"
            pname = spec.get("parameter") or "?"
            lines.append(
                f"| {parameter_md_link(pname, prefix='../../')} | {off_txt} | "
                f"`{spec.get('encoding')}` | {spec.get('kind')} |"
            )

    lines.extend(
        [
            "",
            "[All presets](../) · [Program identity](../../program-identity.md)",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )
    return "\n".join(lines)


def _render_preset_section(
    dump: dict[str, Any],
    *,
    param_names: list[str],
    today: str,
    sheet_compare: dict[str, Any] | None = None,
    link_prefix: str = "../../",
    standalone: bool = False,
) -> list[str]:
    from ..preset_sheet import COMPARABLE, sheet_status_for_dump

    bank = dump["bank"]
    preset = dump["preset"]
    _, preset_slug = preset_slugs(bank, preset)
    params = dump.get("parameters") or {}
    sheet_status = sheet_status_for_dump(sheet_compare, bank, preset)
    comparison = sheet_status.get("comparison")

    lines: list[str] = []
    if not standalone:
        lines.extend(
            [
                f'<a id="{preset_slug}"></a>',
                "",
                f"## {preset}",
                "",
            ]
        )
    if not standalone:
        lines.extend(
            [
                f"_Source: `sysex/prog/presets/{dump.get('file')}`._",
                "",
            ]
        )
    lines.extend(
        [
            "### Identity",
            "",
            "| Field | Value |",
            "|-------|-------|",
            f"| Bank | {bank} (index {dump.get('bank_index')}) |",
            f"| Program slot | {dump.get('program_slot')} |",
            f"| Name field | `{dump.get('name_field')}` "
            f"{_name_match_label(dump)} |",
            f"| Name bytes 8-87 | {_name_bytes_label(dump)} |",
            f"| Dump file | `{dump.get('file')}` |",
            "",
        ]
    )

    if dump.get("name_mismatch"):
        mm = dump["name_mismatch"]
        lines.extend(
            [
                "> **Name byte mismatch:** SysEx offsets 8-87 do not match the "
                f"filename preset `{dump.get('preset')}` "
                f"(field shows `{dump.get('name_field')}`). "
                f"First difference at offset {mm.get('offset')} "
                f"(expected `{mm.get('expected_byte')}`, "
                f"got `{mm.get('actual_byte')}`).",
                "",
            ]
        )

    lines.extend(_preset_sheet_callout(sheet_status, link_prefix=link_prefix))

    if param_names and params:
        lines.extend(
            _preset_parameters_section(
                param_names,
                params,
                comparison=comparison,
                comparable=COMPARABLE,
                link_prefix=link_prefix,
            )
        )
    return lines


def _render_preset_page(
    dump: dict[str, Any],
    *,
    all_dumps: list[dict[str, Any]],
    bank_siblings: list[dict[str, Any]],
    param_names: list[str],
    decoders: list[dict[str, Any]],
    today: str,
    sheet_compare: dict[str, Any] | None = None,
) -> str:
    """Standalone preset page under presets/<bank>/<preset>.md."""
    bank = dump["bank"]
    preset = dump["preset"]
    bank_slug, preset_slug = preset_slugs(bank, preset)
    lines = [
        _page_nav(depth=2, current="Program identity"),
        f"# {preset}",
        "",
        f"_Generated {today}. Bank: [{bank}](README.md) (index "
        f"**{dump.get('bank_index')}**). Source: "
        f"`sysex/prog/presets/{dump.get('file')}`._",
        "",
        "[All presets](../../README.md) · "
        f"[{bank} bank](README.md) · "
        "[Program identity](../../program-identity.md)",
        "",
    ]
    lines.extend(
        _render_preset_section(
            dump,
            param_names=param_names,
            today=today,
            sheet_compare=sheet_compare,
            link_prefix="../../",
            standalone=True,
        )
    )
    if len(bank_siblings) > 1:
        lines.extend(["## Other presets in this bank", ""])
        for sib in bank_siblings:
            sib_slug = preset_slugs(sib["bank"], sib["preset"])[1]
            if sib["preset"] == preset:
                lines.append(f"- **{sib['preset']}** (this page)")
            else:
                lines.append(f"- [{sib['preset']}]({sib_slug}.md)")
        lines.append("")
    lines.append(f"_Last exported: {today}_")
    lines.append("")
    return "\n".join(lines)


def _render_names_page(
    names: dict[str, Any],
    *,
    today: str,
    sheet_compare: dict[str, Any] | None = None,
) -> str:
    """Overview page for program identity + links into presets/."""
    from ..decode_preset import PARAMETER_ORDER, short_name

    fields = names.get("fields") or {}
    bank = fields.get("bank_index") or {}
    program = fields.get("program_slot") or {}
    name_field = fields.get("program_name") or {}
    hyp = names.get("hypothesis") or {}

    lines: list[str] = [
        _page_nav(depth=0, current="Program identity"),
        "# Program identity",
        "",
        f"_Generated {today}. Source folder: `sysex/prog/presets/` "
        f"({names.get('dump_count', 0)} dumps named "
        f"`{names.get('naming_convention', '<bank>.<preset>.syx')}`)._",
        "",
        f"**Confidence:** {hyp.get('confidence', '?')}",
        "",
        hyp.get("summary") or "",
        "",
        "Decoded parameters: **[presets/](presets/)** (bank pages + "
        "[presets.json](presets/presets.json)).",
        "",
    ]
    if sheet_compare:
        lines.extend(
            [
                f"Published-sheet comparison: **[preset-sheet.md](preset-sheet.md)** "
                f"({sheet_compare.get('hard_count', 0)} hard / "
                f"{sheet_compare.get('soft_only_count', 0)} soft-only discrepancies).",
                "",
            ]
        )
    lines.extend(
        [
        "## Fields",
        "",
        f"- **Program name** offsets **{name_field.get('offset_range', '8-87')}** "
        f"(`{name_field.get('encoding', 'ascii_space_padded')}`). "
        f"Filename check: "
        f"{name_field.get('bytes_match_count', '?')}/"
        f"{names.get('dump_count', '?')} dumps match "
        f"(mismatch count {name_field.get('bytes_mismatch_count', '?')}). "
        f"{name_field.get('notes', '')}",
        f"- **Bank index** offsets **{'-'.join(str(o) for o in bank.get('offsets', [88, 89]))}** "
        f"(`{bank.get('encoding', 'nibble_hilo')}`). "
        f"{bank.get('notes', '')}",
        f"- **Program slot** offsets **{'-'.join(str(o) for o in program.get('offsets', [90, 91]))}** "
        f"(`{program.get('encoding', 'nibble_hilo')}`). "
        f"{program.get('notes', '')}",
        "",
        ]
    )

    mismatches = names.get("name_mismatches") or []
    if mismatches:
        lines.extend(
            [
                "## Name byte mismatches",
                "",
                "SysEx offsets 8-87 must equal the filename preset as ASCII, "
                "space-padded to 80 bytes.",
                "",
                "| File | Filename preset | Name field | First bad offset |",
                "|------|-----------------|------------|-----------------:|",
            ]
        )
        for mm in mismatches:
            detail = mm.get("mismatch") or {}
            lines.append(
                f"| `{mm.get('file')}` | `{mm.get('preset')}` | "
                f"`{mm.get('name_field')}` | {detail.get('offset', '-')} |"
            )
        lines.append("")

    lines.extend(
        [
            "## Bank index map",
            "",
            "| Bank | Encoded | Bytes 88-89 | Mirror 137 | Presets |",
            "|------|--------:|-------------|------------|---------|",
        ]
    )

    from ..names import bank_map_sorted_by_index

    bank_map = bank.get("map") or {}
    dump_by_bank: dict[str, list[dict[str, Any]]] = {}
    for d in names.get("dumps") or []:
        dump_by_bank.setdefault(d["bank"], []).append(d)
    for bank_name, idx in bank_map_sorted_by_index(bank_map):
        dumps = dump_by_bank.get(bank_name) or []
        d0 = dumps[0] if dumps else {}
        b88 = (d0.get("bytes") or {}).get("88", "??")
        b89 = (d0.get("bytes") or {}).get("89", "??")
        mir = (d0.get("bytes") or {}).get("137", "??")
        bank_slug, _ = preset_slugs(bank_name, (dumps[0]["preset"] if dumps else "x"))
        lines.append(
            f"| [{bank_name}](presets/{bank_slug}/) | {idx} | `{b88}` `{b89}` | "
            f"`{mir}` | {len(dumps)} |"
        )

    sorted_dumps = sorted(
        names.get("dumps") or [],
        key=lambda row: (row.get("bank_index", 0), row.get("program_slot", 0)),
    )

    lines.extend(
        [
            "",
            "## Captured presets",
            "",
            "| Bank | Preset | Slot | Name bytes | Docs |",
            "|------|--------|-----:|------------|------|",
        ]
    )
    for d in sorted_dumps:
        bank_slug, preset_slug = preset_slugs(d["bank"], d["preset"])
        href = f"presets/{bank_slug}/{preset_slug}.md"
        name_ok = "ok" if d.get("name_bytes_match") else "MISMATCH"
        lines.append(
            f"| [{d.get('bank')}](presets/{bank_slug}/) | "
            f"[{d.get('preset')}]({href}) | {d.get('program_slot')} | "
            f"{name_ok} | [open]({href}) |"
        )

    by_bank = program.get("by_bank") or {}
    if by_bank:
        lines.extend(["", "## Program slots by bank", ""])
        for bank_name, presets in by_bank.items():
            bank_slug, _ = preset_slugs(
                bank_name, next(iter(presets.keys()), "x")
            )
            lines.append(f"### [{bank_name}](presets/{bank_slug}/)")
            lines.append("")
            lines.append("| Slot | Preset |")
            lines.append("|-----:|--------|")
            for preset_name, slot in presets.items():
                _bs, ps = preset_slugs(bank_name, preset_name)
                lines.append(
                    f"| {slot} | [{preset_name}](presets/{_bs}/{ps}.md) |"
                )
            lines.append("")

    param_names = [
        p
        for p in PARAMETER_ORDER
        if any(p in (d.get("parameters") or {}) for d in sorted_dumps)
    ]
    if param_names and names.get("parameters_decoded"):
        lines.extend(
            [
                "## Summary matrix",
                "",
                "Decoded from each dump using the densified encoding map (series, "
                "`provided` UI walks, sheet anchors). Cell values are labeled dump "
                "readings; `~` only when a step falls between witnesses. Detail: "
                "[presets/](presets/).",
                "",
            ]
        )
        header = (
            "| Bank | Preset | "
            + " | ".join(
                f"[{short_name(p)}](parameters/{parameter_slug(p)}.md)"
                for p in param_names
            )
            + " |"
        )
        sep = "|------|--------|" + "|".join("---" for _ in param_names) + "|"
        lines.append(header)
        lines.append(sep)
        for d in sorted_dumps:
            params = d.get("parameters") or {}
            cells = [
                bank_md_link(d["bank"]),
                preset_md_link(d["bank"], d["preset"]),
            ]
            for p in param_names:
                cells.append(str((params.get(p) or {}).get("display", "-")))
            lines.append("| " + " | ".join(cells) + " |")
        lines.append("")

        lines.extend(
            [
                "## Decoder sources",
                "",
                "| Parameter | Offsets | Encoding | Kind |",
                "|-----------|---------|----------|------|",
            ]
        )
        for spec in names.get("parameter_decoders") or []:
            offs = spec.get("offsets") or []
            if len(offs) == 1:
                off_txt = str(offs[0])
            elif offs:
                off_txt = f"{offs[0]}-{offs[-1]}"
            else:
                off_txt = "-"
            pname = spec.get("parameter") or "?"
            lines.append(
                f"| {parameter_md_link(pname)} | {off_txt} | "
                f"`{spec.get('encoding')}` | {spec.get('kind')} |"
            )
        lines.append("")

    for note in names.get("bank_hint_notes") or []:
        lines.append(f"- Catalog hint note: {note}")

    lines.append("")
    lines.append(f"_Last exported: {today}_")
    lines.append("")
    return "\n".join(lines)


def _summary_row(result: dict[str, Any]) -> str:
    best = result.get("best_encoding") or {}
    hyp = result.get("hypothesis") or {}
    value_range = result.get("value_range") or {}

    offsets = best.get("offsets") or result.get("classification", {}).get(
        "parameter_candidate_offsets", []
    )
    offset_txt = _fmt_offsets(offsets)
    encoding = best.get("encoding", "-")
    notes = _short_notes(best)
    range_txt = value_range.get("summary") or "-"
    confidence = hyp.get("confidence", "-")
    dumps = result.get("dump_count", 0)
    name = result["parameter"]
    slug = parameter_slug(name)
    return (
        f"| **[{name}](parameters/{slug}.md)** | {offset_txt} | `{encoding}` | {notes} | "
        f"{range_txt} | {confidence} | {dumps} |"
    )


def _render_sheet_only_parameter_page(decoder: dict[str, Any], *, today: str) -> str:
    """Stub page for parameters located via presets × sheet (no series folder yet)."""
    from ..catalog import lookup_parameter

    name = decoder["parameter"]
    offsets = decoder.get("offsets") or []
    off_txt = _fmt_offsets(offsets)
    enc = decoder.get("encoding") or "?"
    kind = decoder.get("kind") or "?"
    notes = decoder.get("notes") or ""
    conf = decoder.get("confidence") or "medium"
    mapping = decoder.get("mapping") or {}
    lines = [
        _page_nav(depth=1),
        f"# {name.title()}",
        "",
        f"_Generated {today}. **Preset×sheet only** — no "
        f"`sysex/prog/parameters/{name}/` capture series yet._",
        "",
    ]
    catalog = lookup_parameter(name)
    if catalog:
        lines.extend(_parameter_description_section(catalog))
    lines.extend(
        [
            "## Location",
            "",
            f"- **Offsets:** {off_txt}",
            f"- **Encoding:** `{enc}` ({kind})",
            f"- **Confidence:** {conf}",
            f"- **Source:** `{decoder.get('source', 'preset_sheet')}`",
            "",
        ]
    )
    if notes:
        lines.extend(["## Notes", "", notes, ""])
    if kind == "affine":
        scale = decoder.get("scale")
        add = decoder.get("offset")
        lines.extend(
            [
                "## Mapping",
                "",
                f"`label = {scale} × encoded + ({add})`",
                "",
            ]
        )
    elif mapping:
        lines.extend(
            [
                "## Sparse table (from sheet-matched presets)",
                "",
                "| Encoded | Label |",
                "|--------:|------:|",
            ]
        )
        unit = decoder.get("unit")
        for enc_v, label in sorted(mapping.items()):
            if unit == "hz":
                cell = f"{int(label)} Hz" if float(label).is_integer() else f"{label} Hz"
            else:
                cell = str(label)
            lines.append(f"| {enc_v} | {cell} |")
        lines.append("")
    lines.extend(
        [
            "## Next step",
            "",
            f"Capture a dedicated `sysex/prog/parameters/{name}/` series (extremes + adjacent + "
            "mids) and re-run `python run.py` so this page is replaced by a "
            "full series analysis.",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )
    return "\n".join(lines)


def _parameter_description_section(
    official: dict[str, Any] | None,
    *,
    parameter: str | None = None,
) -> list[str]:
    """Official manual prose for a parameter page (before dump tables)."""
    meta = dict(official or {})
    if not meta.get("description") and parameter:
        from ..catalog import lookup_parameter

        catalog = lookup_parameter(parameter)
        if catalog and catalog.get("description"):
            meta = catalog
    if not meta.get("description"):
        return []
    lines = [
        "## Description",
        "",
        str(meta["description"]),
        "",
    ]
    sources = list(meta.get("description_sources") or [])
    if not sources:
        cite = meta.get("description_source")
        url = meta.get("description_url")
        if cite and url:
            sources = [(cite, url)]
        elif cite:
            sources = [(cite, None)]
    if sources:
        parts = []
        for cite, url in sources:
            if url:
                parts.append(f"[{cite}]({url})")
            else:
                parts.append(str(cite))
        lines.append(f"_Source: {'; '.join(parts)}._")
        lines.append("")
    return lines


def _parameter_display_name(name: str, *, kind: str = "prog") -> str:
    if kind == "system":
        from ..system.catalog import lookup_system_parameter

        catalog = lookup_system_parameter(name)
    else:
        from ..catalog import lookup_parameter

        catalog = lookup_parameter(name)
    return (catalog or {}).get("name") or name.title()


def _parameter_synopsis(
    result: dict[str, Any],
    *,
    kind: str = "prog",
) -> list[str]:
    """At-a-glance offsets, encoding, confidence, range, byte-map link."""
    best = result.get("best_encoding") or {}
    hyp = result.get("hypothesis") or {}
    offsets = best.get("offsets") or []
    encoding = best.get("encoding") or "?"
    conf = hyp.get("confidence") or "?"
    lines = [
        "## SysEx summary",
        "",
        f"- **Offsets:** {_fmt_offsets(offsets) if offsets else '—'}",
        f"- **Encoding:** `{encoding}`",
        f"- **Confidence:** {conf}",
    ]
    value_range = result.get("value_range") or {}
    if value_range.get("summary"):
        lines.append(f"- **Range:** {value_range['summary']}")
    if kind == "system":
        lines.append(
            "- **Layout:** [system byte map](../byte-map.md)"
        )
    else:
        slug = parameter_slug(result["parameter"])
        lines.append(
            "- **Layout:** [byte map overview](../byte-map-overview.md) · "
            "[full map](../byte-map.md)"
        )
    lines.append("")
    return lines


def _provided_coverage_note(
    parameter: str,
    *,
    sysex_root: Path | None,
    kind: str = "prog",
) -> list[str]:
    from ..provided import has_provided_labels

    if has_provided_labels(parameter, sysex_root=sysex_root):
        return []
    family = "program parameter" if kind == "prog" else "system setting"
    suffix = (
        " — mid-steps may be **inferred** from the confirmed affine scale "
        "between sparse dumps and factory preset anchors."
        if kind == "prog"
        else "."
    )
    return [
        "> **Capture note:** No hardware UI walk in "
        "`docs/reference/provided_labels.json` yet for this "
        f"{family} — encoding map is built from sparse labeled dumps{suffix}",
        "",
    ]


def _render_parameter_page(
    result: dict[str, Any],
    *,
    all_results: list[dict[str, Any]],
    today: str,
    sysex_root: Path | None = None,
) -> str:
    name = result["parameter"]
    display = _parameter_display_name(name, kind="prog")
    lines: list[str] = [
        _page_nav(depth=1),
        f"# {display}",
        "",
        f"_Generated {today}. Source folder: `sysex/prog/parameters/{name}/`._",
        "",
    ]
    lines.extend(_parameter_synopsis(result, kind="prog"))
    lines.extend(
        _provided_coverage_note(name, sysex_root=sysex_root, kind="prog")
    )
    lines.extend(
        _parameter_description_section(
            result.get("official"), parameter=name
        )
    )
    lines.extend(
        [
            _parameter_body(result, sysex_root=sysex_root),
            "",
            "## Other parameters",
            "",
        ]
    )
    for other in all_results:
        other_name = other["parameter"]
        slug = parameter_slug(other_name)
        other_display = _parameter_display_name(other_name, kind="prog")
        if other_name == name:
            lines.append(f"- **{other_display}** (this page)")
        else:
            lines.append(f"- [{other_display}]({slug}.md)")
    lines.append("")
    return "\n".join(lines)


def _parameter_body(
    result: dict[str, Any],
    *,
    sysex_root: Path | None = None,
) -> str:
    """Parameter dump table + interpretation (no H1/H2 title)."""
    best = result.get("best_encoding")
    hyp = result.get("hypothesis") or {}
    value_range = result.get("value_range")
    secondary = result.get("classification", {}).get("secondary_offsets") or []
    checksum = result.get("classification", {}).get("checksum_candidate_offsets") or []

    lines: list[str] = []

    if best:
        densified = _full_encoding_rows(result, best, sysex_root=sysex_root)
        if densified:
            lines.append("## Encoding map")
            lines.append("")
            lines.append(_encoding_map_table(result, best, densified))
            appendix = _preset_witnesses_appendix(densified)
            if appendix:
                lines.append("")
                lines.append(appendix)
            lines.append("")
            lines.append("### Captured dumps")
            lines.append("")
            lines.append(
                "Sparse series used as anchors (plus secondary/checksum bytes "
                "that moved with this capture stream):"
            )
            lines.append("")
            lines.append(_dump_table(result, best, include_source=True))
        else:
            lines.append(_dump_table(result, best, include_source=True))
        lines.append("")
        lines.append("## Interpretation")
        lines.append("")
        lines.append(
            f"- **Primary field:** offsets **{_fmt_offsets(best['offsets'])}**, "
            f"encoding `{best['encoding']}`"
            + (f" ({_short_notes(best)})" if _short_notes(best) != "-" else "")
            + "."
        )
        conf = hyp.get("confidence", "unknown")
        score = best.get("score")
        if score is not None:
            lines.append(
                f"- **Confidence:** {conf} "
                f"({best.get('matched', '?')}/{best.get('total', '?')} dumps matched, "
                f"{score:.0%})."
            )
        else:
            lines.append(f"- **Confidence:** {conf}.")
        official = result.get("official") or {}
        if official.get("matched"):
            exp = official.get("expected") or {}
            lines.append(
                f"- **Catalog hint (Bricasti):** {official.get('name')} - "
                f"printed {exp.get('manual_min')} ... {exp.get('manual_max')}"
                + (f" {exp['unit']}" if exp.get("unit") else "")
                + f" [{official.get('agreement', '?')}]"
                + " - hint only; dumps win."
            )
            if official.get("notes"):
                lines.append(f"- **Catalog notes:** {official['notes']}")
            for note in official.get("notes_from_check") or []:
                lines.append(f"- **Catalog note:** {note}")
            for warn in official.get("warnings") or []:
                lines.append(f"- **Catalog warning:** {warn}")
        elif official.get("warning"):
            lines.append(f"- **Catalog:** {official['warning']}")
        if value_range and value_range.get("summary"):
            lines.append(f"- **Range:** {value_range['summary']}.")
            if value_range.get("balance"):
                lines.append(
                    f"- **Display:** {value_range['balance']['display']}."
                )
            for which, title in (("off", "OFF"), ("low", "LOW"), ("high", "HIGH/FULL")):
                ep = value_range.get(which)
                if not ep or "encoded_value" not in ep:
                    continue
                if "inferred_label_display" in ep:
                    extra = f" (label {ep['inferred_label_display']})"
                elif "inferred_label" in ep:
                    extra = f" (label {ep['inferred_label']})"
                elif ep.get("note"):
                    extra = f" - {ep['note']}"
                else:
                    extra = ""
                lines.append(
                    f"- **{title} endpoint:** `{ep['file']}` -> encoded "
                    f"{ep['encoded_value']}{extra}."
                )
        sampling = result.get("sampling") or {}
        coverage = sampling.get("coverage") or {}
        if coverage:
            parts = []
            if coverage.get("has_extreme_low") and coverage.get("has_extreme_high"):
                parts.append("extremes")
            if coverage.get("has_adjacent_low") and coverage.get("has_adjacent_high"):
                parts.append("adjacents")
            if coverage.get("mid_count"):
                parts.append(
                    f"{coverage['mid_count']} sample mid(s) "
                    "(not every step)"
                )
            if parts:
                lines.append(f"- **Sampling:** {', '.join(parts)}.")
        edge = (value_range or {}).get("edge_steps") or sampling.get("edge_steps") or {}
        if edge.get("note"):
            lines.append(f"- **Edge slopes:** {edge['note']}")
        how = (hyp.get("how_to_set") or {}).get("encode_steps") or []
        if how:
            lines.append("- **How to set:**")
            for i, step in enumerate(how, start=1):
                lines.append(f"  {i}. {step}")
        if secondary:
            lines.append(
                f"- **Secondary offsets:** {_fmt_offsets(secondary)} "
                "(likely edit/UI state, not the parameter word)."
            )
        if checksum:
            cs_range = _checksum_range_desc(result)
            lines.append(
                f"- **Checksum nibbles:** {_fmt_offsets(checksum)} "
                f"(CRC-16/ARC over {cs_range}, packed high-nibble-first)."
            )
    else:
        lines.append("_No encoding hypothesis yet - need more labeled dumps._")

    lines.append("")
    return "\n".join(lines)


def _format_encoding_label(result: dict[str, Any], row: dict[str, Any]) -> str:
    """Human label for one densified encoding row (balance A/B, units)."""
    from ..encoding_map_rows import format_row_display_label

    return format_row_display_label(result, row)


def _is_table_encoding(best: dict[str, Any]) -> bool:
    from ..encoding_map_rows import is_table_encoding

    return is_table_encoding(best)


def _series_numeric_mapping(result: dict[str, Any], best: dict[str, Any]) -> dict[int, float]:
    from ..encoding_map_rows import series_numeric_mapping

    return series_numeric_mapping(result, best)


def _synthetic_affine_provided_mapping(
    series: dict[int, float],
    special: dict[int, str],
    scale: float,
    offset: float,
) -> dict[int, float]:
    from ..encoding_map_rows import synthetic_affine_provided_mapping

    return synthetic_affine_provided_mapping(series, special, scale, offset)


def _series_special_labels(result: dict[str, Any]) -> dict[int, str]:
    from ..encoding_map_rows import series_special_labels

    return series_special_labels(result)


def _full_encoding_rows(
    result: dict[str, Any],
    best: dict[str, Any],
    *,
    sysex_root: Path | None,
) -> list[dict[str, Any]] | None:
    from ..encoding_map_rows import full_encoding_rows

    return full_encoding_rows(result, best, sysex_root=sysex_root)


def _checksum_range_desc(result: dict[str, Any]) -> str:
    """Human checksum cover range for interpretation bullets."""
    from ..frame import PROG_CHECKSUM_RANGE_DESC, SYSTEM_CHECKSUM_RANGE_DESC

    if result.get("kind") == "system":
        return SYSTEM_CHECKSUM_RANGE_DESC
    return PROG_CHECKSUM_RANGE_DESC


def _preset_link(bank: str, preset: str, index: int) -> str:
    bank_slug, preset_slug = preset_slugs(bank, preset)
    return f"[{index}](../presets/{bank_slug}/{preset_slug}.md)"


def _format_encoding_source(
    row: dict[str, Any],
    *,
    max_preset_links: int = MAX_INLINE_PRESET_LINKS,
) -> str:
    """Render Source cell; list every witness, comma-separated.

    When many presets witness one step, inline only the first *max_preset_links*
    and append a ``+N more`` suffix. Full lists appear in
    :func:`_preset_witnesses_appendix`.
    """
    sources = list(row.get("sources") or [])
    if not sources and row.get("source"):
        sources = [str(row["source"])]
    parts: list[str] = []
    for source in sources:
        if source == "preset":
            refs = row.get("preset_refs") or []
            if not refs:
                parts.append("preset")
                continue
            for i, (bank, preset) in enumerate(refs[:max_preset_links], start=1):
                parts.append(_preset_link(bank, preset, i))
            extra = len(refs) - max_preset_links
            if extra > 0:
                parts.append(f"+{extra} more")
        else:
            parts.append(str(source))
    return ", ".join(parts)


def _preset_witnesses_appendix(
    densified: list[dict[str, Any]],
    *,
    max_inline: int = MAX_INLINE_PRESET_LINKS,
) -> str:
    """Full preset witness lists for encoding rows with collapsed inline links."""
    sections: list[str] = []
    for row in densified:
        refs = row.get("preset_refs") or []
        if len(refs) <= max_inline:
            continue
        enc = int(row["encoded"])
        by_bank: dict[str, list[str]] = {}
        for bank, preset in refs:
            by_bank.setdefault(bank, []).append(
                preset_md_link(bank, preset, prefix="../", page=True)
            )
        bank_parts = [
            f"**{bank}:** {', '.join(links)}"
            for bank, links in sorted(by_bank.items())
        ]
        sections.append(f"- **{enc}:** " + "; ".join(bank_parts))
    if not sections:
        return ""
    lines = [
        "### Preset witnesses",
        "",
        "Factory presets that witness encoded steps with more than "
        f"{max_inline} matches (collapsed in the table above):",
        "",
        *sections,
    ]
    return "\n".join(lines)


def _encoding_map_table(
    result: dict[str, Any],
    best: dict[str, Any],
    densified: list[dict[str, Any]],
) -> str:
    """Full encoded→label map with Source (dump / provided / preset)."""
    from ..preset_inferred import pack_encoded_bytes

    primary = list(best["offsets"])
    headers = ["Encoded"]
    for off in primary:
        headers.append(f"Offset {off}")
    headers.extend(["Label", "Source"])

    lines = [
        ENCODING_MAP_INTRO_SHORT,
        "",
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]

    for row in densified:
        enc = int(row["encoded"])
        nibbles = pack_encoded_bytes(enc, best["encoding"], len(primary))
        label = _format_encoding_label(result, row)
        cells = [str(enc)]
        cells.extend(f"`{b}`" for b in nibbles)
        # Pad if encoding produced fewer bytes than primary offsets.
        while len(cells) < 1 + len(primary):
            cells.append("-")
        cells.append(label)
        cells.append(_format_encoding_source(row))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _dump_table(
    result: dict[str, Any],
    best: dict[str, Any],
    *,
    include_source: bool = False,
) -> str:
    primary = list(best["offsets"])
    secondary = result.get("classification", {}).get("secondary_offsets") or []
    checksum = result.get("classification", {}).get("checksum_candidate_offsets") or []
    series_unit = result.get("unit")

    headers = ["Label"]
    for off in primary:
        headers.append(f"Offset {off}")
    if len(primary) >= 2:
        headers.append(f"`{best['encoding']}`")
    elif primary:
        headers.append("Encoded")
    for off in secondary:
        headers.append(f"Offset {off}")
    if checksum:
        headers.append(
            f"Checksum {checksum[0]}-{checksum[-1]}"
            if len(checksum) > 1
            else f"Checksum {checksum[0]}"
        )
    if include_source:
        headers.append("Source")

    rows = ["| " + " | ".join(headers) + " |"]
    rows.append("| " + " | ".join("---" for _ in headers) + " |")

    for dump in result.get("dumps") or []:
        label = _dump_label_cell(dump, series_unit=series_unit)
        cells = [label]
        changing = dump.get("changing_bytes") or {}
        for off in primary:
            cells.append(f"`{changing.get(str(off), '??')}`")
        decoded = dump.get("decoded_parameter") or {}
        if "encoded_value" in decoded:
            cells.append(str(decoded["encoded_value"]))
        elif primary:
            cells.append("-")
        for off in secondary:
            cells.append(f"`{changing.get(str(off), '??')}`")
        if checksum:
            cs = " ".join(f"`{changing.get(str(off), '??')}`" for off in checksum)
            cells.append(cs)
        if include_source:
            cells.append("dump")
        rows.append("| " + " | ".join(cells) + " |")

    return "\n".join(rows)


def _dump_label_cell(dump: dict[str, Any], series_unit: str | None = None) -> str:
    from ..labels import format_value_with_unit

    label = dump.get("label") or {}
    kind = label.get("kind")
    unit = label.get("unit") or series_unit
    decoded = dump.get("decoded_parameter") or {}

    if label.get("pair"):
        from ..labels import format_balance_pair

        a, b = label["pair"]
        return format_balance_pair(a, b)
    if kind == "endpoint":
        name = label.get("stem") or label.get("endpoint") or label.get("value")
        inferred = decoded.get("inferred_label")
        if inferred is not None:
            return f"{name} ({format_value_with_unit(inferred, unit)})"
        return str(name)
    if kind == "number":
        return format_value_with_unit(label.get("value"), unit)
    if kind == "bool":
        return "on" if label.get("value") else "off"
    return str(label.get("stem") or dump.get("file") or "?")


def _fmt_offsets(offsets: list[int]) -> str:
    if not offsets:
        return "-"
    if len(offsets) == 1:
        return str(offsets[0])
    runs: list[str] = []
    start = prev = offsets[0]
    for off in offsets[1:]:
        if off == prev + 1:
            prev = off
            continue
        runs.append(str(start) if start == prev else f"{start}-{prev}")
        start = prev = off
    runs.append(str(start) if start == prev else f"{start}-{prev}")
    return ", ".join(runs)


def _short_notes(best: dict[str, Any] | None) -> str:
    if not best:
        return "-"
    notes = best.get("notes") or ""
    primary = notes.split(";", 1)[0].strip()
    if primary.startswith("label = encoded * 1"):
        return "identity"
    if primary.startswith("label = "):
        return primary.removeprefix("label = ").strip()
    if not primary:
        return "-"
    return primary


