"""SYSTEM dump documentation export."""

from __future__ import annotations

import shutil
from datetime import date
from pathlib import Path
from typing import Any

from ..system.byte_map import (
    render_system_byte_map_markdown,
    render_system_byte_map_overview_markdown,
)
from ..system.kaitai_spec import write_system_dump_spec
from .nav import (
    SYSTEM_BYTES_DIR,
    _system_page_nav,
    parameter_slug,
    resolve_export_dir,
    system_export_dir,
    system_parameter_page_path,
)
from .open_items import SYSTEM_OPEN_ITEMS, render_open_items_section
from .prog import (
    _fmt_offsets,
    _parameter_body,
    _parameter_description_section,
    _parameter_display_name,
    _parameter_synopsis,
    _promote_h1,
    _provided_coverage_note,
)

SYSTEM_DOC_HEADER = """# M7 system-dump SysEx format

Community reverse-engineered specification for **SYSTEM** dumps captured while holding **SYSTEM** on the M7. These are I/O and routing settings — not program sound parameters. Not an official Bricasti specification.

> Auto-generated by `python run.py` (or `python -m m7_sysex export`). Re-run after
> adding dumps under `sysex/system/`; do not hand-edit generated pages.

"""

SYSTEM_FRAME_SECTION = """## Frame layout

Observed length: **{message_length} bytes** for the captured system dumps.

| Offset | Size | Content |
|--------|------|---------|
| 0 | 1 | `F0` SysEx start |
| 1-3 | 3 | Manufacturer ID `{mfr}` (Bricasti Design) |
| 4-7 | 4 | Header `{header}` (**SYSTEM** family; byte 6 is `02` vs `01` on PROG) |
| 8-71 | 64 | System payload as **nibbles** (`0x00`-`0x0F`) — **no** 80-byte ASCII name |
| 72-75 | 4 | Checksum: **CRC-16/ARC** over offsets 8-71, packed as four high-nibble-first bytes |
| 76 | 1 | `F7` SysEx end |

```
F0 | {mfr} | {header} | <system payload nibbles> | <4 nibble cs> | F7
```

### Notes

- Same nibble packing and checksum algorithm as program dumps, but a shorter message
  with a different header and no program-name field.
- Each `sysex/system/<series>/` folder is an independent capture stream (same
  convention as program parameter folders).
- Program-dump analysis, byte map, and Kaitai spec **do not** include these offsets.

## Series map

| Series | Offsets | Encoding | Confidence | Dumps |
|--------|---------|----------|------------|-------|
"""


def export_system_format(
    system_results: list[dict[str, Any]],
    output_path: Path,
    *,
    byte_map: dict[str, Any] | None = None,
) -> Path | None:
    """Write ``specification/system/`` (overview + one page per series)."""
    if not system_results:
        return None

    output_root = resolve_export_dir(output_path)
    system_dir = system_export_dir(output_root)
    if system_dir.exists():
        shutil.rmtree(system_dir)
    legacy_params = system_dir / "parameters"
    if legacy_params.is_dir():
        shutil.rmtree(legacy_params)
    params_dir = system_dir / SYSTEM_BYTES_DIR
    params_dir.mkdir(parents=True)

    sorted_results = sorted(system_results, key=lambda r: r["parameter"])
    today = date.today().isoformat()
    frame = sorted_results[0]["frame"]
    mfr = frame["manufacturer_id"]
    header = frame["header"]
    message_length = sorted_results[0]["message_length"]

    overview = _render_system_overview(
        sorted_results,
        byte_map=byte_map,
        mfr=mfr,
        header=header,
        message_length=message_length,
        today=today,
    )
    overview_path = system_dir / "README.md"
    overview_path.write_text(overview, encoding="utf-8")

    for result in sorted_results:
        page = _render_system_series_page(
            result,
            all_results=sorted_results,
            today=today,
            sysex_root=Path(sorted_results[0]["folder"]).parent.parent,
        )
        system_parameter_page_path(system_dir, result["parameter"]).write_text(
            page, encoding="utf-8"
        )

    from .parameters_index import build_system_parameters_readme

    (params_dir / "README.md").write_text(
        build_system_parameters_readme(sorted_results, today=today),
        encoding="utf-8",
    )

    if byte_map:
        overview_body = _promote_h1(
            render_system_byte_map_overview_markdown(byte_map)
        )
        (system_dir / "byte-map-overview.md").write_text(
            _system_page_nav(depth=0, current="Byte map")
            + overview_body
            + f"\n\n_Last exported: {today}_\n",
            encoding="utf-8",
        )
        body = _promote_h1(render_system_byte_map_markdown(byte_map))
        (system_dir / "byte-map.md").write_text(
            _system_page_nav(depth=0) + body + f"\n\n_Last exported: {today}_\n",
            encoding="utf-8",
        )
        write_system_dump_spec(system_dir, byte_map, sorted_results)

    return overview_path


def _system_summary_row(result: dict[str, Any]) -> str:
    best = result.get("best_encoding") or {}
    offsets = _fmt_offsets(best.get("offsets") or [])
    encoding = best.get("encoding") or "?"
    conf = (result.get("hypothesis") or {}).get("confidence") or "?"
    return (
        f"| {result['parameter'].title()} | {offsets} | `{encoding}` | "
        f"{conf} | {result['dump_count']} |"
    )


def _render_system_overview(
    results: list[dict[str, Any]],
    *,
    byte_map: dict[str, Any] | None,
    mfr: str,
    header: str,
    message_length: int,
    today: str,
) -> str:
    parts = [
        _system_page_nav(depth=0, current="System overview"),
        SYSTEM_DOC_HEADER,
        SYSTEM_FRAME_SECTION.format(
            message_length=message_length,
            mfr=mfr,
            header=header,
        ),
    ]
    for result in results:
        parts.append(_system_summary_row(result) + "\n")

    if byte_map:
        counts = byte_map["counts"]
        parts.extend(
            [
                "\n## Byte coverage\n\n",
                f"System layout is **{counts['total']} bytes**. "
                "Full table: [byte-map.md](byte-map.md) · "
                "short overview: [byte-map-overview.md](byte-map-overview.md). "
                "Codegen: [m7_system_dump.ksy](m7_system_dump.ksy) / "
                "[m7_system_dump.spec.json](m7_system_dump.spec.json).\n\n",
                f"| Status | Bytes |\n|--------|------:|\n",
                f"| Known / frame / checksum | {counts['known_or_frame']} |\n",
                f"| Secondary | {counts['secondary']} |\n",
                f"| Unknown | {counts['unknown']} |\n",
            ]
        )

    parts.append(
        "\n## Series pages\n\n"
        "Index with descriptions: [bytes/README.md](bytes/README.md).\n\n"
    )
    for result in results:
        name = result["parameter"]
        slug = parameter_slug(name)
        conf = (result.get("hypothesis") or {}).get("confidence") or "?"
        parts.append(f"- [{name.title()}](bytes/{slug}.md) ({conf})\n")

    parts.append(
        "\n## Capture notes\n\n"
        "- **Audio routing:** offset 13 (`raw_u8`); Stereo=0, Mono L=1, Mono R=2.\n"
        "- **Display level:** primary field @ offset 21; offset 25 also moves in this series (secondary).\n"
        "- **MIDI channel:** encoded 0-15 maps to channels 1-16; `omni` uses encoded 16.\n"
        "- **Output level:** primary byte at offset 17 (`raw_u8` values 0, 1, 2 for UI 8/16/24).\n"
        "- **Wet gain:** offsets 8–9 (`nibble_hilo`); Off/Full are discrete; "
        "numbered settings are 0.5 dB steps from −60 dB to 0 dB (Full).\n"
        "- **Dry gain:** offsets 10–11 (`nibble_hilo`); Off/Full are discrete; "
        "numbered settings are 0.5 dB steps from −60 dB to 0 dB (Full).\n"
    )
    parts.append(f"\n_Last exported: {today}_\n")
    parts.append(render_open_items_section(SYSTEM_OPEN_ITEMS))
    return "".join(parts)


def _render_system_series_page(
    result: dict[str, Any],
    *,
    all_results: list[dict[str, Any]],
    today: str,
    sysex_root: Path | None = None,
) -> str:
    name = result["parameter"]
    display = _parameter_display_name(name, kind="system")
    lines: list[str] = [
        _system_page_nav(depth=1, current="System overview"),
        f"# {display}",
        "",
        f"_Generated {today}. Source folder: `sysex/system/{name}/`._",
        "",
    ]
    lines.extend(_parameter_synopsis(result, kind="system"))
    from ..system.catalog import lookup_system_parameter

    catalog = lookup_system_parameter(name)
    if catalog:
        lines.extend(
            _parameter_description_section(
                {
                    "description": catalog.get("description"),
                    "description_source": catalog.get("description_source"),
                    "description_url": catalog.get("description_url"),
                }
            )
        )
    lines.extend(
        _provided_coverage_note(name, sysex_root=sysex_root, kind="system")
    )
    if result.get("duplicate_byte_notes"):
        lines.extend(
            [
                "> **Note:** " + result["duplicate_byte_notes"],
                "",
            ]
        )
    best = result.get("best_encoding")
    if best:
        lines.extend(_parameter_body(result, sysex_root=None).splitlines())
    else:
        lines.append(
            "No encoding fit found for numeric or enum labels in this series."
        )
        lines.append("")

    lines.extend(["", "## Other system series", ""])
    for other in all_results:
        other_name = other["parameter"]
        slug = parameter_slug(other_name)
        other_display = _parameter_display_name(other_name, kind="system")
        if other_name == name:
            lines.append(f"- **{other_display}** (this page)")
        else:
            lines.append(f"- [{other_display}]({slug}.md)")
    lines.append("")
    return "\n".join(lines)
