"""Export PROG front-panel UI state documentation."""

from __future__ import annotations

from typing import Any

from ..prog.display import nibble_hilo as _nibble_hilo


def _fmt_cursor_bytes(hi: int, lo: int) -> str:
    return f"`{hi:02X} {lo:02X}`"


def render_ui_state_markdown(
    menus_analysis: dict[str, Any],
    *,
    today: str,
    nav: str = "",
) -> str:
    prog_ui = menus_analysis["prog_ui"]
    idle = prog_ui["idle"]
    menu_order = prog_ui["menu_order"]
    by_param = prog_ui["by_parameter"]

    idle_cursor = _nibble_hilo(idle["146"], idle["147"])

    lines = [
        nav,
        "# Program UI state (front-panel menu)",
        "",
        "Offsets in the 157-byte **program** dump that reflect front-panel "
        "navigation and edit cursor — not sound parameters. Derived from "
        "`sysex/prog/menus/` captures (menu highlight only, values unchanged).",
        "",
        "> Auto-generated by `python run.py`. Do not hand-edit.",
        "",
        "## Idle (no menu open)",
        "",
        "Baseline from `no menu.syx` — use when loading a preset or changing "
        "multiple parameters at once.",
        "",
        "| Offset | Value | Role |",
        "|--------|------:|------|",
        f"| 92 | `{idle['92']:02X}` | menu browse flag (`00` = idle) |",
        f"| 98–99 | `{idle['98']:02X} {idle['99']:02X}` | menu index (`00` = none) |",
        (
            f"| 146–147 | {_fmt_cursor_bytes(idle['146'], idle['147'])} | "
            f"display (`nibble_hilo` = {idle_cursor}; page={idle['146']}, "
            f"pos={idle['147']}) |"
        ),
        "",
        "**Note:** Reverb Time highlighted also uses menu index `0` at 98–99; "
        "discriminate with `92 = 02` (menu open) vs `92 = 00` (idle).",
        "",
        "## Menu index (`nibble_hilo` @ 98–99)",
        "",
        "Hardware menu order (owner's manual / catalog):",
        "",
        (
            "| Index | Parameter | Browse `92` | Browse 146–147 | "
            "`nibble_hilo` |"
        ),
        "|------:|-----------|------------:|---------------:|-----------:|",
    ]

    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        browse = row.get("browse") or {}
        b92 = browse.get("92")
        b146 = browse.get("146")
        b147 = browse.get("147")
        if browse:
            cursor = _nibble_hilo(b146, b147)
            lines.append(
                f"| {i} | {name} | "
                f"`{b92:02X}` | {_fmt_cursor_bytes(b146, b147)} | {cursor} |"
            )
        else:
            lines.append(f"| {i} | {name} | — | — | — |")

    lines.extend(
        [
            "",
            "## Display (`nibble_hilo` @ 146–147)",
            "",
            "LCD cursor / edit-display position. High nibble (offset 146) = "
            "page/row; low nibble (offset 147) = column/position. Browse "
            "values for indices 1–17 follow `menu_index + 28` except reverb "
            "time highlight (index 0 → `0x2E`).",
            "",
            "## Edit mode (single parameter change)",
            "",
            "When the user turns a control (not just highlighting the menu), "
            "captures use `92 = 00` with the same menu index at 98–99. "
            "Typical 146–147 from parameter series:",
            "",
            "| Index | Parameter | Edit 146–147 | `nibble_hilo` |",
            "|------:|-----------|--------------|-------------:|",
        ]
    )

    edit_rows: list[tuple[int, str]] = []
    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        edit_rows.append((int(row.get("index", i)), name))
    for index, name in sorted(edit_rows, key=lambda item: item[0]):
        row = by_param.get(name) or {}
        edit = row.get("edit")
        if not edit:
            lines.append(f"| {index} | {name} | — | — |")
            continue
        hi = int(edit.get("146", 0))
        lo = int(edit.get("147", 0))
        lines.append(
            f"| {index} | {name} | {_fmt_cursor_bytes(hi, lo)} | "
            f"{_nibble_hilo(hi, lo)} |"
        )

    lines.extend(
        [
            "",
            "## Related",
            "",
            "- [Byte map overview](byte-map-overview.md) — layout and offsets",
            "- [Program UI state](ui-state.md) — full menu browse/edit tables",
            "- [Capture guide](../../docs/capture-guide.md) — how to record menu dumps",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )

    return "\n".join(lines)


def render_display_parameter_page(
    menus_analysis: dict[str, Any],
    *,
    today: str,
    nav: str = "",
) -> str:
    """Parameter-style page for offsets 146–147 (`nibble_hilo` display)."""
    prog_ui = menus_analysis["prog_ui"]
    idle = prog_ui["idle"]
    menu_order = prog_ui["menu_order"]
    by_param = prog_ui["by_parameter"]
    capture_count = menus_analysis.get("capture_count", 0)

    idle_cursor = _nibble_hilo(idle["146"], idle["147"])
    browse_rows: list[dict[str, object]] = [
        {
            "label": "idle (`no menu`)",
            "hi": int(idle["146"]),
            "lo": int(idle["147"]),
            "cursor": idle_cursor,
        }
    ]
    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        browse = row.get("browse") or {}
        if not browse:
            continue
        hi = int(browse["146"])
        lo = int(browse["147"])
        browse_rows.append(
            {
                "label": f"browse: {name} ({i})",
                "hi": hi,
                "lo": lo,
                "cursor": _nibble_hilo(hi, lo),
            }
        )
    browse_rows.sort(key=lambda r: int(r["cursor"]))

    edit_rows: list[dict[str, object]] = []
    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        edit = row.get("edit")
        if not edit:
            edit_rows.append(
                {"index": i, "name": name, "hi": None, "lo": None, "cursor": None}
            )
            continue
        hi = int(edit.get("146", 0))
        lo = int(edit.get("147", 0))
        edit_rows.append(
            {
                "index": i,
                "name": name,
                "hi": hi,
                "lo": lo,
                "cursor": _nibble_hilo(hi, lo),
            }
        )
    edit_rows.sort(key=lambda r: (r["cursor"] is None, int(r["cursor"] or 0)))

    lines = [
        nav,
        "# Display",
        "",
        f"_Generated {today}. Source folder: `sysex/prog/menus/` "
        f"({capture_count} captures)._",
        "",
        "## SysEx summary",
        "",
        "- **Offsets:** 146–147",
        "- **Encoding:** `nibble_hilo` — combined value `(byte[146] << 4) | byte[147]`",
        "- **Confidence:** high",
        "- **Role:** LCD cursor / edit-display position (not a sound parameter)",
        "- **Layout:** [byte map overview](../byte-map-overview.md) · "
        "[full map](../byte-map.md)",
        "",
        "## Description",
        "",
        "Front-panel cursor position packed as two nibbles in the program dump. "
        "High nibble (offset 146) is the page/row while browsing (`92 = 02`) or "
        "the edit anchor while changing a value (`92 = 00`). Low nibble "
        "(offset 147) is the column/position within the menu page, or the "
        "value-display position while editing.",
        "",
        "Menu index remains authoritative at offsets **98–99**. See "
        "[Program UI state](../ui-state.md) for idle/browse/edit tables across "
        "all UI bytes.",
        "",
        "## Encoding map",
        "",
        "Witness sources: menu-navigation captures only (parameter values held "
        "constant). Wire bytes shown as two nibbles; decoded column is "
        "`nibble_hilo`.",
        "",
        "| Label | Offset 146 | Offset 147 | `nibble_hilo` | Source |",
        "|-------|------------|------------|--------------:|--------|",
    ]
    for row in browse_rows:
        lines.append(
            f"| {row['label']} | `{int(row['hi']):02X}` | `{int(row['lo']):02X}` | "
            f"{int(row['cursor'])} | dump |"
        )

    lines.extend(
        [
            "",
            "### Edit mode witnesses",
            "",
            "Typical cursor bytes while turning a control (from parameter series "
            "dumps with `92 = 00`):",
            "",
            "| Index | Parameter | Offset 146 | Offset 147 | `nibble_hilo` |",
            "|------:|-----------|------------|------------|--------------:|",
        ]
    )

    for row in edit_rows:
        if row["cursor"] is None:
            lines.append(f"| {row['index']} | {row['name']} | — | — | — |")
            continue
        hi = int(row["hi"])
        lo = int(row["lo"])
        lines.append(
            f"| {row['index']} | {row['name']} | `{hi:02X}` | `{lo:02X}` | "
            f"{int(row['cursor'])} |"
        )

    from ..prog.unseen_values import display_unseen
    from .unseen_values import render_display_unseen_section

    lines.append("")
    lines.extend(render_display_unseen_section(display_unseen(menus_analysis)))

    lines.extend(
        [
            "## Interpretation",
            "",
            "- **Primary field:** offsets **146–147**, encoding `nibble_hilo`.",
            "- **Confidence:** high — consistent across `sysex/prog/menus/` captures.",
            "- **How to set:**",
            "  1. `byte[146] = (value >> 4) & 0x0F`",
            "  2. `byte[147] = value & 0x0F`",
            "  3. Recompute trailing checksum: CRC-16/ARC over bytes[8:152], "
            "packed as four high-nibble-first SysEx bytes at offsets 152–155",
            "",
            "## Related",
            "",
            "- [Program UI state](../ui-state.md)",
            "- [Byte map overview](../byte-map-overview.md)",
            "- [Capture guide](../../../docs/capture-guide.md)",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )

    return "\n".join(lines)
