"""Export PROG front-panel UI state documentation."""

from __future__ import annotations

from typing import Any

from ..prog.display import nibble_hilo as _nibble_hilo


def _fmt_cursor_bytes(hi: int, lo: int) -> str:
    return f"`{hi:02X} {lo:02X}`"


def _edit_band(row: dict[str, Any]) -> dict[str, Any] | None:
    band = row.get("edit_band")
    return band if isinstance(band, dict) else None


def render_ui_state_markdown(
    menus_analysis: dict[str, Any],
    *,
    today: str,
    nav: str = "",
) -> str:
    prog_ui = menus_analysis["prog_ui"]
    idle = prog_ui["idle"]
    menu_order = prog_ui["menu_order"]
    by_param = prog_ui["by_parameter"]
    corpus = menus_analysis.get("display_corpus") or {}

    idle_cursor = _nibble_hilo(idle["146"], idle["147"])

    lines = [
        nav,
        "# Program UI state (front-panel menu)",
        "",
        "Offsets in the 157-byte **program** dump that reflect front-panel "
        "navigation and edit cursor — not sound parameters. Derived from "
        "`sysex/prog/menus/` captures (menu highlight only, values unchanged) "
        "plus edit-mode bands from `sysex/prog/parameters/`.",
        "",
        "> Auto-generated by `python run.py`. Do not hand-edit.",
        "",
        "## Idle (no menu open)",
        "",
        "Baseline from `no menu.syx` — use when loading a preset or changing "
        "multiple parameters at once.",
        "",
        "| Offset | Value | Role |",
        "|--------|------:|------|",
        f"| 92 | `{idle['92']:02X}` | panel mode flag (`00` = idle; "
        f"`08` = favorites screen, see `sysex/prog/favorites/`) |",
        f"| 98–99 | `{idle['98']:02X} {idle['99']:02X}` | menu index (`00` = none) |",
        (
            f"| 146–147 | {_fmt_cursor_bytes(idle['146'], idle['147'])} | "
            f"display (`nibble_hilo` = {idle_cursor}; browse idle code) |"
        ),
        "",
        "**Note:** Reverb Time highlighted also uses menu index `0` at 98–99; "
        "discriminate with `92 = 02` (menu open) vs `92 = 00` (idle).",
        "",
        "## Menu index (`nibble_hilo` @ 98–99)",
        "",
        "Hardware menu order (owner's manual / catalog):",
        "",
        (
            "| Index | Parameter | Browse `92` | Browse 146–147 | "
            "`nibble_hilo` |"
        ),
        "|------:|-----------|------------:|---------------:|-----------:|",
    ]

    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        browse = row.get("browse") or {}
        b92 = browse.get("92")
        b146 = browse.get("146")
        b147 = browse.get("147")
        if browse:
            cursor = _nibble_hilo(b146, b147)
            lines.append(
                f"| {i} | {name} | "
                f"`{b92:02X}` | {_fmt_cursor_bytes(b146, b147)} | {cursor} |"
            )
        else:
            lines.append(f"| {i} | {name} | — | — | — |")

    lines.extend(
        [
            "",
            "## Display (`nibble_hilo` @ 146–147)",
            "",
            "Front-panel UI focus code (not a sound parameter). "
            "**Browse** (`92 = 02`): stable menu-row highlight — indices 1–17 "
            "follow `menu_index + 28`; reverb time (index 0) → `0x2E` (46); "
            "idle → 28. "
            "**Edit** (`92 = 00`): value-focus code in a parameter-specific "
            "band that advances as the shown value changes — not a fixed "
            "per-parameter anchor. See [bytes/display.md](bytes/display.md).",
            "",
            "## Edit mode (single parameter change)",
            "",
            "When the user turns a control (not just highlighting the menu), "
            "captures use `92 = 00` with the same menu index at 98–99. "
            "Observed **display bands** from each parameter series "
            "(min–max `nibble_hilo`; sample is one mid dump, not a fixed "
            "anchor):",
            "",
            (
                "| Index | Parameter | Band | Unique | Sample 146–147 | "
                "Sample `nibble_hilo` |"
            ),
            "|------:|-----------|-----:|-------:|----------------|-------------:|",
        ]
    )

    edit_rows: list[tuple[int, str]] = []
    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        edit_rows.append((int(row.get("index", i)), name))
    for index, name in sorted(edit_rows, key=lambda item: item[0]):
        row = by_param.get(name) or {}
        band = _edit_band(row)
        edit = row.get("edit")
        if not band and not edit:
            lines.append(f"| {index} | {name} | — | — | — | — |")
            continue
        if band:
            sample = band.get("sample") or {}
            hi = int(sample.get("hi", edit.get("146", 0) if edit else 0))
            lo = int(sample.get("lo", edit.get("147", 0) if edit else 0))
            lines.append(
                f"| {index} | {name} | {band['min']}–{band['max']} | "
                f"{band['unique']}/{band['dumps']} | "
                f"{_fmt_cursor_bytes(hi, lo)} | {_nibble_hilo(hi, lo)} |"
            )
        else:
            hi = int(edit.get("146", 0))
            lo = int(edit.get("147", 0))
            lines.append(
                f"| {index} | {name} | — | — | {_fmt_cursor_bytes(hi, lo)} | "
                f"{_nibble_hilo(hi, lo)} |"
            )

    if corpus.get("edit_code_collisions"):
        lines.extend(
            [
                "",
                "Some edit-mode display codes appear under more than one "
                "parameter (discriminate with 98–99): "
                + ", ".join(
                    f"`{c['display']}` ({', '.join(c['parameters'])})"
                    for c in corpus["edit_code_collisions"][:8]
                )
                + (
                    "…"
                    if len(corpus["edit_code_collisions"]) > 8
                    else ""
                )
                + ".",
            ]
        )

    lines.extend(
        [
            "",
            "## Related",
            "",
            "- [Byte map overview](byte-map-overview.md) — layout and offsets",
            "- [Display](bytes/display.md) — browse map, edit bands, hypotheses",
            "- [Capture guide](../../docs/capture-guide.md) — how to record menu dumps",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )

    return "\n".join(lines)


def render_display_parameter_page(
    menus_analysis: dict[str, Any],
    *,
    today: str,
    nav: str = "",
) -> str:
    """Parameter-style page for offsets 146–147 (`nibble_hilo` display)."""
    prog_ui = menus_analysis["prog_ui"]
    idle = prog_ui["idle"]
    menu_order = prog_ui["menu_order"]
    by_param = prog_ui["by_parameter"]
    capture_count = menus_analysis.get("capture_count", 0)
    corpus = menus_analysis.get("display_corpus") or {}

    idle_cursor = _nibble_hilo(idle["146"], idle["147"])
    browse_rows: list[dict[str, object]] = [
        {
            "label": "idle (`no menu`)",
            "hi": int(idle["146"]),
            "lo": int(idle["147"]),
            "cursor": idle_cursor,
        }
    ]
    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        browse = row.get("browse") or {}
        if not browse:
            continue
        hi = int(browse["146"])
        lo = int(browse["147"])
        browse_rows.append(
            {
                "label": f"browse: {name} ({i})",
                "hi": hi,
                "lo": lo,
                "cursor": _nibble_hilo(hi, lo),
            }
        )
    browse_rows.sort(key=lambda r: int(r["cursor"]))

    lines = [
        nav,
        "# Display",
        "",
        f"_Generated {today}. Source folder: `sysex/prog/menus/` "
        f"({capture_count} captures) + edit bands from "
        f"`sysex/prog/parameters/`._",
        "",
        "## SysEx summary",
        "",
        "- **Offsets:** 146–147",
        "- **Encoding:** `nibble_hilo` — combined value `(byte[146] << 4) | byte[147]`",
        "- **Confidence:** high (UI field / not sound); edit-band geometry medium",
        "- **Role:** Front-panel UI focus code (not a sound parameter)",
        "- **Layout:** [byte map overview](../byte-map-overview.md) · "
        "[full map](../byte-map.md)",
        "",
        "## Description",
        "",
        "Packed UI focus code in the program dump. Discriminate modes with "
        "offset **92** (panel mode) and the menu index at **98–99**.",
        "",
        "- **Browse** (`92 = 02`): stable **menu-row highlight** code. "
        "Indices 1–17 use `menu_index + 28`; reverb time (index 0) uses "
        "**46**; idle uses **28**.",
        "- **Edit** (`92 = 00`): **value-focus** code inside a "
        "parameter-specific band. The code advances as the shown value "
        "changes (often only offset 147 until nibble wrap). It is **not** a "
        "fixed per-parameter edit anchor, not `encoding + constant`, and not "
        "1:1 with large wire-encoding steps.",
        "",
        "Safe to ignore when patching sound parameters (already treated as a "
        "secondary mover). Factory presets often latch a non-browse display "
        "value from the last UI focus.",
        "",
        "## Encoding map (browse)",
        "",
        "Witness sources: menu-navigation captures only (parameter values held "
        "constant). Wire bytes shown as two nibbles; decoded column is "
        "`nibble_hilo`.",
        "",
        "| Label | Offset 146 | Offset 147 | `nibble_hilo` | Source |",
        "|-------|------------|------------|--------------:|--------|",
    ]
    for row in browse_rows:
        lines.append(
            f"| {row['label']} | `{int(row['hi']):02X}` | `{int(row['lo']):02X}` | "
            f"{int(row['cursor'])} | dump |"
        )

    lines.extend(
        [
            "",
            "### Edit mode bands",
            "",
            "Observed `nibble_hilo` ranges while turning a control "
            "(`92 = 00`, matching menu index at 98–99). Sparse series — "
            "bands are lower bounds on the true span. Sample is one mid dump, "
            "not a fixed anchor. Sorted by band minimum:",
            "",
            (
                "| Index | Parameter | Band | Unique/dumps | Monotonic | "
                "Sample 146–147 | Sample `nibble_hilo` |"
            ),
            (
                "|------:|-----------|-----:|-------------:|:---------:|"
                "----------------|-------------------:|"
            ),
        ]
    )

    band_rows: list[dict[str, Any]] = []
    for i, name in enumerate(menu_order):
        row = by_param.get(name) or {}
        band = _edit_band(row)
        edit = row.get("edit")
        if not band and not edit:
            continue
        if band:
            sample = band.get("sample") or {}
            hi = int(sample.get("hi", 0))
            lo = int(sample.get("lo", 0))
            band_rows.append(
                {
                    "index": i,
                    "name": name,
                    "min": int(band["min"]),
                    "max": int(band["max"]),
                    "unique": band["unique"],
                    "dumps": band["dumps"],
                    "mono": band.get("monotonic"),
                    "hi": hi,
                    "lo": lo,
                    "cursor": _nibble_hilo(hi, lo),
                }
            )
        else:
            hi = int(edit.get("146", 0))
            lo = int(edit.get("147", 0))
            band_rows.append(
                {
                    "index": i,
                    "name": name,
                    "min": _nibble_hilo(hi, lo),
                    "max": _nibble_hilo(hi, lo),
                    "unique": 1,
                    "dumps": 1,
                    "mono": True,
                    "hi": hi,
                    "lo": lo,
                    "cursor": _nibble_hilo(hi, lo),
                }
            )
    band_rows.sort(key=lambda r: (r["min"], r["index"]))

    for row in band_rows:
        mono = "yes" if row["mono"] else "no"
        lines.append(
            f"| {row['index']} | {row['name']} | "
            f"{row['min']}–{row['max']} | "
            f"{row['unique']}/{row['dumps']} | {mono} | "
            f"{_fmt_cursor_bytes(row['hi'], row['lo'])} | {row['cursor']} |"
        )

    from ..prog.unseen_values import display_unseen
    from .unseen_values import render_display_unseen_section

    lines.append("")
    lines.extend(render_display_unseen_section(display_unseen(menus_analysis)))

    hypotheses = corpus.get("hypotheses") or []
    open_items = corpus.get("open") or []
    collisions = corpus.get("edit_code_collisions") or []

    lines.extend(
        [
            "## Interpretation",
            "",
            "- **Primary field:** offsets **146–147**, encoding `nibble_hilo`.",
            "- **Confidence:** high that this is ephemeral UI state (not "
            "sound); **medium** for edit-mode band / value-focus geometry.",
            "- **Browse:** menu-row highlight codes (see encoding map).",
            "- **Edit:** parameter-specific value-focus bands (see table); "
            "reject fixed edit-anchor and second-parameter-word readings.",
            "- **How to set (when synthesizing UI state):**",
            "  1. `byte[146] = (value >> 4) & 0x0F`",
            "  2. `byte[147] = value & 0x0F`",
            "  3. Recompute trailing checksum: CRC-16/ARC over bytes[8:152], "
            "packed as four high-nibble-first SysEx bytes at offsets 152–155",
            "",
        ]
    )

    if hypotheses:
        lines.extend(["### Hypothesis ranking", ""])
        for h in hypotheses:
            lines.append(
                f"- **{h['id']}** — `{h['verdict']}` "
                f"({h['confidence']}): {h['summary']}"
            )
        lines.append("")

    if collisions:
        lines.extend(
            [
                "### Edit-code collisions",
                "",
                "Same display code witnessed under multiple parameters while "
                "editing (use 98–99 to disambiguate):",
                "",
            ]
        )
        for c in collisions:
            lines.append(
                f"- `{c['display']}`: {', '.join(c['parameters'])}"
            )
        lines.append("")

    if open_items:
        lines.extend(["### Open", ""])
        for item in open_items:
            lines.append(f"- {item}")
        lines.append("")

    lines.extend(
        [
            "## Related",
            "",
            "- [Program UI state](../ui-state.md)",
            "- [Byte map overview](../byte-map-overview.md)",
            "- [Capture guide](../../../docs/capture-guide.md)",
            "",
            f"_Last exported: {today}_",
            "",
        ]
    )

    return "\n".join(lines)
